extends RefCounted
class_name GameDefs

const PLANT_ORDER = [
	"peashooter",
	"sunflower",
	"cherry_bomb",
	"wallnut",
	"potato_mine",
	"snow_pea",
	"chomper",
	"repeater",
	"amber_shooter",
	"vine_lasher",
	"pepper_mortar",
	"cactus_guard",
	"pulse_bulb",
	"sun_bean",
	"wind_orchid",
]

const PLANTS = {
	"peashooter": {
		"name": "豌豆射手",
		"cost": 100,
		"cooldown": 7.5,
		"health": 120.0,
		"shoot_interval": 1.4,
		"damage": 20.0,
	},
	"sunflower": {
		"name": "向日葵",
		"cost": 50,
		"cooldown": 7.5,
		"health": 100.0,
		"sun_interval": 24.0,
		"first_sun_delay": 8.0,
	},
	"cherry_bomb": {
		"name": "樱桃炸弹",
		"cost": 150,
		"cooldown": 30.0,
		"health": 999.0,
		"fuse": 0.75,
		"radius": 155.0,
	},
	"wallnut": {
		"name": "坚果墙",
		"cost": 50,
		"cooldown": 30.0,
		"health": 4000.0,
	},
	"potato_mine": {
		"name": "土豆地雷",
		"cost": 25,
		"cooldown": 30.0,
		"health": 80.0,
		"arm_time": 15.0,
		"radius": 70.0,
	},
	"snow_pea": {
		"name": "寒冰射手",
		"cost": 175,
		"cooldown": 7.5,
		"health": 120.0,
		"shoot_interval": 1.5,
		"damage": 20.0,
		"slow_duration": 10.0,
	},
	"chomper": {
		"name": "大嘴花",
		"cost": 150,
		"cooldown": 7.5,
		"health": 120.0,
		"chew_time": 42.0,
		"range": 92.0,
	},
	"repeater": {
		"name": "双发射手",
		"cost": 200,
		"cooldown": 7.5,
		"health": 120.0,
		"shoot_interval": 1.45,
		"burst_gap": 0.14,
		"damage": 20.0,
		"burst_count": 2,
	},
	"amber_shooter": {
		"name": "琥珀炮花",
		"cost": 125,
		"cooldown": 7.5,
		"health": 120.0,
		"shoot_interval": 1.15,
		"damage": 28.0,
	},
	"vine_lasher": {
		"name": "藤鞭花",
		"cost": 125,
		"cooldown": 10.0,
		"health": 150.0,
		"attack_interval": 1.25,
		"damage": 45.0,
		"range": 120.0,
		"slow_duration": 2.0,
	},
	"pepper_mortar": {
		"name": "辣椒臼炮",
		"cost": 175,
		"cooldown": 12.0,
		"health": 100.0,
		"attack_interval": 2.8,
		"damage": 35.0,
		"splash_radius": 84.0,
	},
	"cactus_guard": {
		"name": "仙人卫",
		"cost": 100,
		"cooldown": 20.0,
		"health": 2400.0,
		"thorns": 16.0,
	},
	"pulse_bulb": {
		"name": "脉冲灯球",
		"cost": 150,
		"cooldown": 10.0,
		"health": 120.0,
		"pulse_interval": 3.6,
		"damage": 30.0,
	},
	"sun_bean": {
		"name": "金豆荚",
		"cost": 75,
		"cooldown": 12.0,
		"health": 110.0,
		"sun_interval": 16.0,
		"first_sun_delay": 7.0,
		"shoot_interval": 1.8,
		"damage": 15.0,
	},
	"wind_orchid": {
		"name": "风兰",
		"cost": 150,
		"cooldown": 18.0,
		"health": 120.0,
		"gust_interval": 7.0,
		"push_distance": 72.0,
	},
	"wallnut_bowling": {
		"name": "坚果保龄球",
		"cost": 0,
		"cooldown": 0.0,
		"health": 1.0,
		"damage": 320.0,
		"roll_speed": 320.0,
	},
}

const ZOMBIES = {
	"normal": {
		"name": "普通僵尸",
		"health": 200.0,
		"speed": 18.0,
		"attack_dps": 24.0,
		"reward": 10,
	},
	"flag": {
		"name": "摇旗僵尸",
		"health": 200.0,
		"speed": 20.0,
		"attack_dps": 24.0,
		"reward": 12,
	},
	"conehead": {
		"name": "路障僵尸",
		"health": 370.0,
		"speed": 18.0,
		"attack_dps": 24.0,
		"reward": 15,
	},
	"pole_vault": {
		"name": "撑杆跳僵尸",
		"health": 340.0,
		"speed": 34.0,
		"post_jump_speed": 18.0,
		"attack_dps": 24.0,
		"reward": 18,
	},
	"buckethead": {
		"name": "铁桶僵尸",
		"health": 1100.0,
		"speed": 16.0,
		"attack_dps": 24.0,
		"reward": 22,
	},
	"farmer": {
		"name": "农夫僵尸",
		"health": 420.0,
		"speed": 20.0,
		"attack_dps": 24.0,
		"reward": 24,
	},
	"spear": {
		"name": "长矛僵尸",
		"health": 340.0,
		"speed": 19.0,
		"attack_dps": 24.0,
		"reward": 24,
	},
	"kungfu": {
		"name": "功夫僵尸",
		"health": 240.0,
		"speed": 18.0,
		"attack_dps": 24.0,
		"reward": 26,
	},
	"day_boss": {
		"name": "昼光机甲",
		"health": 4800.0,
		"speed": 11.0,
		"attack_dps": 40.0,
		"reward": 100,
	},
}

const LEVELS = [
	{
		"id": "1-1",
		"title": "白天 1-1",
		"description": "普通僵尸会从草坪右侧出现。",
		"available_plants": ["peashooter"],
		"unlock_plant": "sunflower",
		"start_sun": 100,
		"row_count": 1,
		"time_scale": 1.65,
		"sky_sun_range": Vector2(4.6, 5.8),
		"node_pos": Vector2(164.0, 626.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 10.0, "kind": "normal"},
			{"time": 14.0, "kind": "normal"},
			{"time": 19.0, "kind": "normal"},
			{"time": 24.0, "kind": "flag", "wave": true},
			{"time": 25.0, "kind": "normal"},
			{"time": 26.0, "kind": "normal"},
		],
	},
	{
		"id": "1-2",
		"title": "白天 1-2",
		"description": "向日葵开始加入防线。",
		"available_plants": ["peashooter", "sunflower"],
		"unlock_plant": "cherry_bomb",
		"start_sun": 50,
		"row_count": 2,
		"time_scale": 1.45,
		"sky_sun_range": Vector2(5.0, 6.2),
		"node_pos": Vector2(318.0, 648.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 9.0, "kind": "normal"},
			{"time": 13.0, "kind": "normal"},
			{"time": 17.0, "kind": "normal"},
			{"time": 21.0, "kind": "flag", "wave": true},
			{"time": 22.0, "kind": "normal"},
			{"time": 24.0, "kind": "normal"},
			{"time": 26.0, "kind": "normal"},
		],
	},
	{
		"id": "1-3",
		"title": "白天 1-3",
		"description": "樱桃炸弹可以瞬间清掉一片僵尸。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb"],
		"unlock_plant": "wallnut",
		"start_sun": 100,
		"row_count": 3,
		"time_scale": 1.3,
		"sky_sun_range": Vector2(5.4, 6.8),
		"node_pos": Vector2(486.0, 618.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 9.0, "kind": "normal"},
			{"time": 13.0, "kind": "normal"},
			{"time": 17.0, "kind": "normal"},
			{"time": 20.0, "kind": "flag", "wave": true},
			{"time": 21.0, "kind": "normal"},
			{"time": 23.0, "kind": "normal"},
			{"time": 28.0, "kind": "normal"},
			{"time": 32.0, "kind": "flag", "wave": true},
			{"time": 33.0, "kind": "normal"},
			{"time": 34.0, "kind": "normal"},
		],
	},
	{
		"id": "1-4",
		"title": "白天 1-4",
		"description": "坚果墙能为后排争取更多输出时间。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut"],
		"unlock_plant": "potato_mine",
		"start_sun": 125,
		"row_count": 4,
		"time_scale": 1.2,
		"sky_sun_range": Vector2(5.8, 7.2),
		"node_pos": Vector2(662.0, 646.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 9.0, "kind": "normal"},
			{"time": 13.0, "kind": "normal"},
			{"time": 17.0, "kind": "normal"},
			{"time": 21.0, "kind": "normal"},
			{"time": 24.0, "kind": "flag", "wave": true},
			{"time": 25.0, "kind": "normal"},
			{"time": 27.0, "kind": "normal"},
			{"time": 31.0, "kind": "normal"},
			{"time": 36.0, "kind": "flag", "wave": true},
			{"time": 37.0, "kind": "normal"},
			{"time": 38.0, "kind": "normal"},
		],
	},
	{
		"id": "1-5",
		"title": "白天 1-5",
		"description": "路障僵尸登场，土豆地雷也能开始埋了。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine"],
		"unlock_plant": "snow_pea",
		"start_sun": 150,
		"row_count": 5,
		"time_scale": 1.15,
		"sky_sun_range": Vector2(6.2, 7.6),
		"node_pos": Vector2(818.0, 612.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 8.0, "kind": "normal"},
			{"time": 12.0, "kind": "conehead"},
			{"time": 15.0, "kind": "normal"},
			{"time": 19.0, "kind": "normal"},
			{"time": 22.0, "kind": "flag", "wave": true},
			{"time": 22.6, "kind": "normal"},
			{"time": 23.2, "kind": "conehead"},
			{"time": 24.0, "kind": "normal"},
			{"time": 29.0, "kind": "conehead"},
			{"time": 33.0, "kind": "normal"},
			{"time": 38.0, "kind": "flag", "wave": true},
			{"time": 38.5, "kind": "conehead"},
			{"time": 39.3, "kind": "normal"},
			{"time": 40.0, "kind": "normal"},
		],
	},
	{
		"id": "1-6",
		"title": "白天 1-6",
		"description": "寒冰射手能稳定减速整条路线的僵尸。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea"],
		"unlock_plant": "chomper",
		"start_sun": 175,
		"row_count": 5,
		"time_scale": 1.1,
		"sky_sun_range": Vector2(6.6, 8.0),
		"node_pos": Vector2(982.0, 640.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 8.0, "kind": "conehead"},
			{"time": 12.0, "kind": "normal"},
			{"time": 15.0, "kind": "normal"},
			{"time": 19.0, "kind": "conehead"},
			{"time": 22.0, "kind": "flag", "wave": true},
			{"time": 22.5, "kind": "normal"},
			{"time": 23.0, "kind": "conehead"},
			{"time": 24.0, "kind": "normal"},
			{"time": 29.0, "kind": "conehead"},
			{"time": 34.0, "kind": "normal"},
			{"time": 39.0, "kind": "conehead"},
			{"time": 44.0, "kind": "flag", "wave": true},
			{"time": 44.5, "kind": "conehead"},
			{"time": 45.2, "kind": "normal"},
			{"time": 46.0, "kind": "conehead"},
		],
	},
	{
		"id": "1-7",
		"title": "白天 1-7",
		"description": "撑杆跳僵尸会越过第一棵植物，大嘴花在近身时很强。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper"],
		"unlock_plant": "repeater",
		"start_sun": 200,
		"row_count": 5,
		"time_scale": 1.08,
		"sky_sun_range": Vector2(6.8, 8.2),
		"node_pos": Vector2(1128.0, 604.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 8.0, "kind": "conehead"},
			{"time": 11.0, "kind": "pole_vault"},
			{"time": 15.0, "kind": "normal"},
			{"time": 19.0, "kind": "conehead"},
			{"time": 22.0, "kind": "flag", "wave": true},
			{"time": 22.6, "kind": "pole_vault"},
			{"time": 23.2, "kind": "normal"},
			{"time": 24.0, "kind": "conehead"},
			{"time": 29.0, "kind": "pole_vault"},
			{"time": 34.0, "kind": "conehead"},
			{"time": 39.0, "kind": "normal"},
			{"time": 46.0, "kind": "flag", "wave": true},
			{"time": 46.4, "kind": "pole_vault"},
			{"time": 47.0, "kind": "conehead"},
			{"time": 47.6, "kind": "normal"},
		],
	},
	{
		"id": "1-8",
		"title": "白天 1-8",
		"description": "铁桶僵尸加入战场，双发射手也会解锁。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater"],
		"unlock_plant": "",
		"start_sun": 200,
		"row_count": 5,
		"time_scale": 1.08,
		"sky_sun_range": Vector2(7.0, 8.4),
		"node_pos": Vector2(1092.0, 476.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 8.0, "kind": "conehead"},
			{"time": 10.0, "kind": "pole_vault"},
			{"time": 14.0, "kind": "buckethead"},
			{"time": 18.0, "kind": "conehead"},
			{"time": 22.0, "kind": "flag", "wave": true},
			{"time": 22.4, "kind": "pole_vault"},
			{"time": 23.0, "kind": "normal"},
			{"time": 25.0, "kind": "buckethead"},
			{"time": 30.0, "kind": "conehead"},
			{"time": 35.0, "kind": "pole_vault"},
			{"time": 40.0, "kind": "buckethead"},
			{"time": 45.0, "kind": "conehead"},
			{"time": 52.0, "kind": "flag", "wave": true},
			{"time": 52.4, "kind": "buckethead"},
			{"time": 53.0, "kind": "pole_vault"},
			{"time": 53.8, "kind": "conehead"},
			{"time": 54.4, "kind": "normal"},
		],
	},
	{
		"id": "1-9",
		"title": "白天 1-9",
		"description": "坚果保龄球关卡，传送带会不断送来坚果。",
		"available_plants": ["wallnut_bowling"],
		"conveyor_plants": ["wallnut_bowling"],
		"unlock_plant": "amber_shooter",
		"mode": "bowling",
		"start_sun": 0,
		"row_count": 5,
		"time_scale": 1.0,
		"sky_sun_range": Vector2(99.0, 99.0),
		"node_pos": Vector2(934.0, 514.0),
		"events": [
			{"time": 4.0, "kind": "normal"},
			{"time": 6.0, "kind": "normal"},
			{"time": 9.0, "kind": "conehead"},
			{"time": 12.0, "kind": "normal"},
			{"time": 15.0, "kind": "buckethead"},
			{"time": 19.0, "kind": "flag", "wave": true},
			{"time": 19.5, "kind": "conehead"},
			{"time": 20.2, "kind": "normal"},
			{"time": 22.0, "kind": "buckethead"},
			{"time": 26.0, "kind": "conehead"},
			{"time": 30.0, "kind": "buckethead"},
			{"time": 34.0, "kind": "flag", "wave": true},
			{"time": 34.4, "kind": "buckethead"},
			{"time": 35.0, "kind": "conehead"},
			{"time": 35.8, "kind": "normal"},
		],
	},
	{
		"id": "1-10",
		"title": "白天 1-10",
		"description": "传送带第一次登场，卡片会自动送到手边。",
		"available_plants": ["peashooter", "wallnut", "potato_mine", "amber_shooter"],
		"conveyor_plants": ["peashooter", "wallnut", "potato_mine", "amber_shooter"],
		"unlock_plant": "vine_lasher",
		"mode": "conveyor",
		"start_sun": 0,
		"row_count": 5,
		"time_scale": 1.0,
		"sky_sun_range": Vector2(99.0, 99.0),
		"node_pos": Vector2(792.0, 472.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 8.0, "kind": "conehead"},
			{"time": 12.0, "kind": "buckethead"},
			{"time": 16.0, "kind": "normal"},
			{"time": 20.0, "kind": "flag", "wave": true},
			{"time": 20.6, "kind": "conehead"},
			{"time": 21.3, "kind": "normal"},
			{"time": 23.0, "kind": "buckethead"},
			{"time": 27.0, "kind": "conehead"},
			{"time": 32.0, "kind": "buckethead"},
			{"time": 37.0, "kind": "flag", "wave": true},
			{"time": 37.6, "kind": "buckethead"},
			{"time": 38.2, "kind": "conehead"},
			{"time": 39.0, "kind": "normal"},
		],
	},
	{
		"id": "1-11",
		"title": "白天 1-11",
		"description": "农夫僵尸会一路抛洒杂草，卡住你的火力线。",
		"available_plants": ["peashooter", "sunflower", "wallnut", "potato_mine", "snow_pea", "repeater", "amber_shooter", "vine_lasher"],
		"unlock_plant": "pepper_mortar",
		"start_sun": 200,
		"row_count": 5,
		"time_scale": 1.0,
		"sky_sun_range": Vector2(6.8, 8.0),
		"node_pos": Vector2(636.0, 514.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 8.0, "kind": "farmer"},
			{"time": 12.0, "kind": "conehead"},
			{"time": 16.0, "kind": "normal"},
			{"time": 20.0, "kind": "farmer"},
			{"time": 24.0, "kind": "flag", "wave": true},
			{"time": 24.6, "kind": "conehead"},
			{"time": 25.2, "kind": "farmer"},
			{"time": 26.0, "kind": "buckethead"},
			{"time": 31.0, "kind": "farmer"},
			{"time": 36.0, "kind": "buckethead"},
			{"time": 42.0, "kind": "flag", "wave": true},
			{"time": 42.6, "kind": "farmer"},
			{"time": 43.1, "kind": "buckethead"},
			{"time": 44.0, "kind": "conehead"},
		],
	},
	{
		"id": "1-12",
		"title": "白天 1-12",
		"description": "长矛僵尸死后会留下埋伏，需要继续清理。",
		"available_plants": ["peashooter", "sunflower", "wallnut", "potato_mine", "snow_pea", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar"],
		"unlock_plant": "cactus_guard",
		"start_sun": 225,
		"row_count": 5,
		"time_scale": 0.98,
		"sky_sun_range": Vector2(6.8, 8.0),
		"node_pos": Vector2(468.0, 484.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 8.0, "kind": "spear"},
			{"time": 11.0, "kind": "conehead"},
			{"time": 15.0, "kind": "spear"},
			{"time": 19.0, "kind": "buckethead"},
			{"time": 23.0, "kind": "flag", "wave": true},
			{"time": 23.7, "kind": "spear"},
			{"time": 24.2, "kind": "normal"},
			{"time": 25.0, "kind": "buckethead"},
			{"time": 30.0, "kind": "spear"},
			{"time": 35.0, "kind": "conehead"},
			{"time": 40.0, "kind": "flag", "wave": true},
			{"time": 40.4, "kind": "buckethead"},
			{"time": 41.0, "kind": "spear"},
			{"time": 41.8, "kind": "normal"},
		],
	},
	{
		"id": "1-13",
		"title": "白天 1-13",
		"description": "功夫僵尸会周期性发动气功，反弹豌豆。",
		"available_plants": ["peashooter", "sunflower", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard"],
		"unlock_plant": "pulse_bulb",
		"start_sun": 250,
		"row_count": 5,
		"time_scale": 0.96,
		"sky_sun_range": Vector2(6.8, 8.0),
		"node_pos": Vector2(298.0, 522.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 8.0, "kind": "kungfu"},
			{"time": 12.0, "kind": "conehead"},
			{"time": 16.0, "kind": "kungfu"},
			{"time": 20.0, "kind": "buckethead"},
			{"time": 24.0, "kind": "flag", "wave": true},
			{"time": 24.6, "kind": "kungfu"},
			{"time": 25.2, "kind": "conehead"},
			{"time": 26.0, "kind": "buckethead"},
			{"time": 31.0, "kind": "kungfu"},
			{"time": 36.0, "kind": "buckethead"},
			{"time": 42.0, "kind": "flag", "wave": true},
			{"time": 42.5, "kind": "kungfu"},
			{"time": 43.1, "kind": "buckethead"},
			{"time": 44.0, "kind": "conehead"},
		],
	},
	{
		"id": "1-14",
		"title": "白天 1-14",
		"description": "三种新僵尸开始混编登场，考验控场与拆障碍能力。",
		"available_plants": ["peashooter", "sunflower", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb"],
		"unlock_plant": "sun_bean",
		"start_sun": 275,
		"row_count": 5,
		"time_scale": 0.94,
		"sky_sun_range": Vector2(6.8, 8.0),
		"node_pos": Vector2(338.0, 364.0),
		"events": [
			{"time": 5.0, "kind": "farmer"},
			{"time": 8.0, "kind": "spear"},
			{"time": 11.0, "kind": "kungfu"},
			{"time": 15.0, "kind": "buckethead"},
			{"time": 19.0, "kind": "conehead"},
			{"time": 24.0, "kind": "flag", "wave": true},
			{"time": 24.6, "kind": "farmer"},
			{"time": 25.0, "kind": "kungfu"},
			{"time": 26.0, "kind": "buckethead"},
			{"time": 31.0, "kind": "spear"},
			{"time": 36.0, "kind": "farmer"},
			{"time": 42.0, "kind": "flag", "wave": true},
			{"time": 42.4, "kind": "buckethead"},
			{"time": 43.1, "kind": "kungfu"},
			{"time": 44.0, "kind": "spear"},
		],
	},
	{
		"id": "1-15",
		"title": "白天 1-15",
		"description": "战线拉长，混编僵尸与重装僵尸同时逼近。",
		"available_plants": ["peashooter", "sunflower", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean"],
		"unlock_plant": "wind_orchid",
		"start_sun": 300,
		"row_count": 5,
		"time_scale": 0.92,
		"sky_sun_range": Vector2(6.8, 8.0),
		"node_pos": Vector2(512.0, 336.0),
		"events": [
			{"time": 5.0, "kind": "farmer"},
			{"time": 8.0, "kind": "buckethead"},
			{"time": 11.0, "kind": "kungfu"},
			{"time": 14.0, "kind": "spear"},
			{"time": 18.0, "kind": "buckethead"},
			{"time": 22.0, "kind": "flag", "wave": true},
			{"time": 22.6, "kind": "farmer"},
			{"time": 23.0, "kind": "kungfu"},
			{"time": 24.0, "kind": "buckethead"},
			{"time": 28.0, "kind": "spear"},
			{"time": 33.0, "kind": "buckethead"},
			{"time": 38.0, "kind": "farmer"},
			{"time": 45.0, "kind": "flag", "wave": true},
			{"time": 45.4, "kind": "buckethead"},
			{"time": 46.0, "kind": "kungfu"},
			{"time": 46.8, "kind": "spear"},
		],
	},
	{
		"id": "1-16",
		"title": "白天 1-16",
		"description": "Boss 关卡，传送带会不断送来植物，昼光机甲会召唤援军。",
		"available_plants": ["wallnut", "potato_mine", "snow_pea", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean", "wind_orchid"],
		"conveyor_plants": ["wallnut", "potato_mine", "snow_pea", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean", "wind_orchid"],
		"unlock_plant": "",
		"mode": "conveyor",
		"boss_level": true,
		"start_sun": 0,
		"row_count": 5,
		"time_scale": 0.88,
		"sky_sun_range": Vector2(99.0, 99.0),
		"node_pos": Vector2(714.0, 378.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 8.0, "kind": "farmer"},
			{"time": 11.0, "kind": "spear"},
			{"time": 14.0, "kind": "kungfu"},
			{"time": 18.0, "kind": "buckethead"},
			{"time": 22.0, "kind": "flag", "wave": true},
			{"time": 22.6, "kind": "farmer"},
			{"time": 23.1, "kind": "spear"},
			{"time": 24.0, "kind": "buckethead"},
			{"time": 29.0, "kind": "kungfu"},
			{"time": 34.0, "kind": "day_boss", "wave": true},
			{"time": 35.2, "kind": "buckethead"},
			{"time": 36.0, "kind": "farmer"},
			{"time": 40.0, "kind": "spear"},
			{"time": 46.0, "kind": "kungfu"},
			{"time": 52.0, "kind": "flag", "wave": true},
			{"time": 52.6, "kind": "buckethead"},
			{"time": 53.0, "kind": "farmer"},
			{"time": 54.0, "kind": "spear"},
		],
	},
]
