extends RefCounted
class_name GameDefs

const PLANT_ORDER = [
	"peashooter",
	"sunflower",
	"cherry_bomb",
	"wallnut",
	"potato_mine",
	"snow_pea",
	"chomper",
	"repeater",
	"amber_shooter",
	"vine_lasher",
	"pepper_mortar",
	"cactus_guard",
	"pulse_bulb",
	"sun_bean",
	"wind_orchid",
	"puff_shroom",
	"sun_shroom",
	"fume_shroom",
	"grave_buster",
	"hypno_shroom",
	"scaredy_shroom",
	"ice_shroom",
	"doom_shroom",
	"moon_lotus",
	"prism_grass",
	"lantern_bloom",
	"meteor_gourd",
	"root_snare",
	"thunder_pine",
	"dream_drum",
	"lily_pad",
	"squash",
	"threepeater",
	"tangle_kelp",
	"jalapeno",
	"spikeweed",
	"torchwood",
	"tallnut",
]

const PLANTS = {
	"peashooter": {
		"name": "豌豆射手",
		"cost": 100,
		"cooldown": 7.5,
		"health": 120.0,
		"shoot_interval": 1.4,
		"damage": 20.0,
	},
	"sunflower": {
		"name": "向日葵",
		"cost": 50,
		"cooldown": 7.5,
		"health": 100.0,
		"sun_interval": 24.0,
		"first_sun_delay": 8.0,
	},
	"cherry_bomb": {
		"name": "樱桃炸弹",
		"cost": 150,
		"cooldown": 30.0,
		"health": 999.0,
		"fuse": 0.75,
		"radius": 155.0,
		"damage": 1600.0,
	},
	"wallnut": {
		"name": "坚果墙",
		"cost": 50,
		"cooldown": 30.0,
		"health": 4000.0,
	},
	"potato_mine": {
		"name": "土豆地雷",
		"cost": 25,
		"cooldown": 30.0,
		"health": 80.0,
		"arm_time": 15.0,
		"radius": 70.0,
		"damage": 1600.0,
	},
	"snow_pea": {
		"name": "寒冰射手",
		"cost": 175,
		"cooldown": 7.5,
		"health": 120.0,
		"shoot_interval": 1.5,
		"damage": 20.0,
		"slow_duration": 10.0,
	},
	"chomper": {
		"name": "大嘴花",
		"cost": 150,
		"cooldown": 7.5,
		"health": 120.0,
		"chew_time": 42.0,
		"range": 92.0,
	},
	"repeater": {
		"name": "双发射手",
		"cost": 200,
		"cooldown": 7.5,
		"health": 120.0,
		"shoot_interval": 1.45,
		"burst_gap": 0.14,
		"damage": 20.0,
		"burst_count": 2,
	},
	"amber_shooter": {
		"name": "琥珀炮花",
		"cost": 125,
		"cooldown": 7.5,
		"health": 120.0,
		"shoot_interval": 1.15,
		"damage": 28.0,
	},
	"vine_lasher": {
		"name": "藤鞭花",
		"cost": 125,
		"cooldown": 10.0,
		"health": 150.0,
		"attack_interval": 1.25,
		"damage": 45.0,
		"range": 220.0,
		"slow_duration": 2.0,
	},
	"pepper_mortar": {
		"name": "辣椒臼炮",
		"cost": 175,
		"cooldown": 12.0,
		"health": 100.0,
		"attack_interval": 2.8,
		"damage": 35.0,
		"splash_radius": 84.0,
	},
	"cactus_guard": {
		"name": "仙人卫",
		"cost": 100,
		"cooldown": 20.0,
		"health": 2400.0,
		"thorns": 16.0,
	},
	"pulse_bulb": {
		"name": "脉冲灯球",
		"cost": 150,
		"cooldown": 10.0,
		"health": 120.0,
		"pulse_interval": 3.6,
		"damage": 30.0,
		"radius": 175.0,
	},
	"sun_bean": {
		"name": "金豆荚",
		"cost": 75,
		"cooldown": 12.0,
		"health": 110.0,
		"sun_interval": 16.0,
		"first_sun_delay": 7.0,
		"shoot_interval": 1.8,
		"damage": 15.0,
	},
	"wind_orchid": {
		"name": "风兰",
		"cost": 150,
		"cooldown": 18.0,
		"health": 120.0,
		"gust_interval": 7.0,
		"push_distance": 44.0,
	},
	"wallnut_bowling": {
		"name": "坚果保龄球",
		"cost": 0,
		"cooldown": 0.0,
		"health": 1.0,
		"damage": 320.0,
		"roll_speed": 320.0,
	},
	"puff_shroom": {
		"name": "小喷菇",
		"cost": 0,
		"cooldown": 7.5,
		"health": 80.0,
		"shoot_interval": 1.3,
		"damage": 20.0,
		"range": 250.0,
	},
	"sun_shroom": {
		"name": "阳光菇",
		"cost": 25,
		"cooldown": 7.5,
		"health": 100.0,
		"sun_interval": 22.0,
		"first_sun_delay": 10.0,
		"grow_time": 42.0,
	},
	"fume_shroom": {
		"name": "大喷菇",
		"cost": 75,
		"cooldown": 7.5,
		"health": 120.0,
		"shoot_interval": 1.9,
		"damage": 28.0,
		"range": 360.0,
		"width": 92.0,
	},
	"grave_buster": {
		"name": "坟墓吞噬者",
		"cost": 75,
		"cooldown": 7.5,
		"health": 999.0,
		"chew_time": 4.2,
	},
	"hypno_shroom": {
		"name": "魅惑菇",
		"cost": 75,
		"cooldown": 30.0,
		"health": 80.0,
	},
	"scaredy_shroom": {
		"name": "胆小菇",
		"cost": 25,
		"cooldown": 7.5,
		"health": 80.0,
		"shoot_interval": 1.55,
		"damage": 20.0,
		"fear_radius": 160.0,
	},
	"ice_shroom": {
		"name": "寒冰菇",
		"cost": 75,
		"cooldown": 50.0,
		"health": 999.0,
		"freeze_duration": 4.0,
		"slow_duration": 10.0,
	},
	"doom_shroom": {
		"name": "毁灭菇",
		"cost": 125,
		"cooldown": 50.0,
		"health": 999.0,
		"radius": 220.0,
		"crater_time": 30.0,
	},
	"moon_lotus": {
		"name": "月光莲",
		"cost": 50,
		"cooldown": 7.5,
		"health": 100.0,
		"sun_interval": 18.0,
		"first_sun_delay": 7.0,
		"wake_interval": 3.2,
		"wake_radius": 145.0,
	},
	"prism_grass": {
		"name": "棱镜草",
		"cost": 125,
		"cooldown": 7.5,
		"health": 120.0,
		"attack_interval": 1.7,
		"damage": 24.0,
		"range": 390.0,
		"slow_duration": 3.0,
		"pierce_count": 3,
	},
	"lantern_bloom": {
		"name": "提灯花",
		"cost": 125,
		"cooldown": 10.0,
		"health": 140.0,
		"pulse_interval": 3.6,
		"damage": 26.0,
		"radius": 140.0,
		"wake_radius": 190.0,
	},
	"meteor_gourd": {
		"name": "陨星葫芦",
		"cost": 175,
		"cooldown": 12.0,
		"health": 120.0,
		"attack_interval": 3.0,
		"damage": 82.0,
		"splash_radius": 82.0,
	},
	"root_snare": {
		"name": "缠根草",
		"cost": 100,
		"cooldown": 10.0,
		"health": 150.0,
		"attack_interval": 2.7,
		"damage": 18.0,
		"range": 260.0,
		"root_duration": 2.8,
	},
	"thunder_pine": {
		"name": "雷松",
		"cost": 175,
		"cooldown": 12.0,
		"health": 120.0,
		"attack_interval": 2.35,
		"damage": 34.0,
		"chain_damage": 18.0,
		"chain_range": 120.0,
	},
	"dream_drum": {
		"name": "醒梦鼓",
		"cost": 150,
		"cooldown": 16.0,
		"health": 180.0,
		"pulse_interval": 5.0,
		"damage": 30.0,
		"radius": 170.0,
		"wake_radius": 280.0,
	},
	"lily_pad": {
		"name": "睡莲",
		"cost": 25,
		"cooldown": 7.5,
		"health": 300.0,
	},
	"squash": {
		"name": "窝瓜",
		"cost": 50,
		"cooldown": 30.0,
		"health": 999.0,
		"range": 120.0,
		"damage": 1600.0,
	},
	"threepeater": {
		"name": "三线射手",
		"cost": 325,
		"cooldown": 7.5,
		"health": 120.0,
		"shoot_interval": 1.5,
		"damage": 20.0,
	},
	"tangle_kelp": {
		"name": "缠绕海草",
		"cost": 25,
		"cooldown": 30.0,
		"health": 90.0,
		"range": 44.0,
		"damage": 1800.0,
	},
	"jalapeno": {
		"name": "火爆辣椒",
		"cost": 125,
		"cooldown": 50.0,
		"health": 999.0,
		"fuse": 0.55,
		"damage": 1600.0,
	},
	"spikeweed": {
		"name": "地刺",
		"cost": 100,
		"cooldown": 7.5,
		"health": 300.0,
		"contact_damage": 20.0,
		"contact_interval": 0.8,
	},
	"torchwood": {
		"name": "火炬树桩",
		"cost": 175,
		"cooldown": 7.5,
		"health": 300.0,
	},
	"tallnut": {
		"name": "高坚果",
		"cost": 125,
		"cooldown": 30.0,
		"health": 8000.0,
	},
}

const ZOMBIES = {
	"normal": {
		"name": "普通僵尸",
		"health": 200.0,
		"speed": 18.0,
		"attack_dps": 24.0,
		"reward": 10,
	},
	"flag": {
		"name": "摇旗僵尸",
		"health": 200.0,
		"speed": 20.0,
		"attack_dps": 24.0,
		"reward": 12,
	},
	"conehead": {
		"name": "路障僵尸",
		"health": 370.0,
		"speed": 18.0,
		"attack_dps": 24.0,
		"reward": 15,
	},
	"pole_vault": {
		"name": "撑杆跳僵尸",
		"health": 340.0,
		"speed": 34.0,
		"post_jump_speed": 18.0,
		"attack_dps": 24.0,
		"reward": 18,
	},
	"buckethead": {
		"name": "铁桶僵尸",
		"health": 1100.0,
		"speed": 16.0,
		"attack_dps": 24.0,
		"reward": 22,
	},
	"farmer": {
		"name": "农夫僵尸",
		"health": 420.0,
		"speed": 20.0,
		"attack_dps": 24.0,
		"reward": 24,
	},
	"spear": {
		"name": "长矛僵尸",
		"health": 340.0,
		"speed": 19.0,
		"attack_dps": 24.0,
		"reward": 24,
	},
	"kungfu": {
		"name": "功夫僵尸",
		"health": 240.0,
		"speed": 18.0,
		"attack_dps": 24.0,
		"reward": 26,
	},
	"day_boss": {
		"name": "昼光机甲",
		"health": 9600.0,
		"speed": 12.0,
		"attack_dps": 56.0,
		"boss": true,
		"reward": 180,
	},
	"night_boss": {
		"name": "暗夜尸王",
		"health": 11800.0,
		"speed": 10.0,
		"attack_dps": 60.0,
		"boss": true,
		"reward": 220,
		"sleep_radius": 150.0,
		"sleep_duration": 5.2,
		"grave_raise_count": 3,
	},
	"newspaper": {
		"name": "读报僵尸",
		"health": 331.0,
		"speed": 12.0,
		"attack_dps": 24.0,
		"reward": 24,
		"shield_health": 150.0,
		"rage_speed": 32.0,
	},
	"screen_door": {
		"name": "铁门僵尸",
		"health": 181.0,
		"speed": 16.0,
		"attack_dps": 24.0,
		"reward": 28,
		"shield_health": 1100.0,
	},
	"football": {
		"name": "橄榄球僵尸",
		"health": 1581.0,
		"speed": 28.0,
		"attack_dps": 28.0,
		"reward": 34,
	},
	"dark_football": {
		"name": "暗黑橄榄球僵尸",
		"health": 3162.0,
		"speed": 28.0,
		"attack_dps": 28.0,
		"reward": 34,
	},
	"dancing": {
		"name": "舞王僵尸",
		"health": 335.0,
		"speed": 16.0,
		"attack_dps": 24.0,
		"reward": 36,
	},
	"backup_dancer": {
		"name": "伴舞僵尸",
		"health": 181.0,
		"speed": 18.0,
		"attack_dps": 24.0,
		"reward": 8,
	},
	"ninja": {
		"name": "忍者僵尸",
		"health": 680.0,
		"speed": 14.0,
		"attack_dps": 24.0,
		"reward": 30,
		"dash_speed": 31.0,
	},
	"basketball": {
		"name": "篮球僵尸",
		"health": 340.0,
		"speed": 23.0,
		"attack_dps": 24.0,
		"reward": 30,
		"shield_health": 220.0,
		"shield_regen_cooldown": 4.4,
	},
	"nezha": {
		"name": "哪吒僵尸",
		"health": 320.0,
		"speed": 18.0,
		"attack_dps": 26.0,
		"reward": 34,
		"burn_dps": 34.0,
	},
	"nether": {
		"name": "冥界僵尸",
		"health": 220.0,
		"speed": 17.0,
		"attack_dps": 24.0,
		"reward": 28,
		"sleep_radius": 155.0,
		"sleep_duration": 4.5,
	},
	"ducky_tube": {
		"name": "游泳圈僵尸",
		"health": 200.0,
		"speed": 18.0,
		"attack_dps": 24.0,
		"reward": 18,
	},
	"lifebuoy_normal": {
		"name": "救生圈僵尸",
		"health": 200.0,
		"speed": 18.0,
		"attack_dps": 24.0,
		"reward": 18,
	},
	"lifebuoy_cone": {
		"name": "路障救生圈僵尸",
		"health": 200.0,
		"shield_health": 170.0,
		"speed": 18.0,
		"attack_dps": 24.0,
		"reward": 22,
	},
	"lifebuoy_bucket": {
		"name": "铁桶救生圈僵尸",
		"health": 200.0,
		"shield_health": 900.0,
		"speed": 16.0,
		"attack_dps": 24.0,
		"reward": 28,
	},
	"snorkel": {
		"name": "潜水僵尸",
		"health": 200.0,
		"speed": 19.0,
		"attack_dps": 24.0,
		"reward": 24,
	},
	"zomboni": {
		"name": "雪橇车僵尸",
		"health": 1350.0,
		"speed": 22.0,
		"attack_dps": 0.0,
		"reward": 42,
	},
	"bobsled_team": {
		"name": "雪橇僵尸小队",
		"health": 760.0,
		"speed": 42.0,
		"attack_dps": 30.0,
		"reward": 40,
		"off_ice_speed": 18.0,
	},
	"dolphin_rider": {
		"name": "海豚骑士僵尸",
		"health": 340.0,
		"speed": 30.0,
		"post_jump_speed": 19.0,
		"attack_dps": 24.0,
		"reward": 30,
	},
	"rumia_boss": {
		"name": "露米娅",
		"health": 12800.0,
		"speed": 0.0,
		"attack_dps": 0.0,
		"boss": true,
		"reward": 260,
		"hover_shift_interval": 2.6,
		"moonlight_damage": 220.0,
		"night_bird_damage": 34.0,
		"darkness_radius": 170.0,
		"summon_count": 3,
	},
	"daiyousei_boss": {
		"name": "大妖精",
		"health": 5600.0,
		"speed": 0.0,
		"attack_dps": 0.0,
		"boss": true,
		"reward": 180,
		"hover_shift_interval": 2.8,
		"ring_damage": 46.0,
		"lance_damage": 180.0,
	},
	"cirno_boss": {
		"name": "琪露诺",
		"health": 13200.0,
		"speed": 0.0,
		"attack_dps": 0.0,
		"boss": true,
		"reward": 280,
		"hover_shift_interval": 2.35,
		"icicle_damage": 110.0,
		"freeze_damage": 86.0,
		"blizzard_damage": 62.0,
	},
}

const LEVELS = [
	{
		"id": "1-1",
		"title": "白天 1-1",
		"description": "普通僵尸会从草坪右侧出现。",
		"available_plants": ["peashooter"],
		"unlock_plant": "sunflower",
		"start_sun": 100,
		"row_count": 1,
		"time_scale": 1.65,
		"sky_sun_range": Vector2(4.6, 5.8),
		"node_pos": Vector2(164.0, 626.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 10.0, "kind": "normal"},
			{"time": 14.0, "kind": "normal"},
			{"time": 19.0, "kind": "normal"},
			{"time": 24.0, "kind": "flag", "wave": true},
			{"time": 25.0, "kind": "normal"},
			{"time": 26.0, "kind": "normal"},
		],
	},
	{
		"id": "1-2",
		"title": "白天 1-2",
		"description": "向日葵开始加入防线。",
		"available_plants": ["peashooter", "sunflower"],
		"unlock_plant": "cherry_bomb",
		"start_sun": 50,
		"row_count": 2,
		"time_scale": 1.45,
		"sky_sun_range": Vector2(5.0, 6.2),
		"node_pos": Vector2(318.0, 648.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 9.0, "kind": "normal"},
			{"time": 13.0, "kind": "normal"},
			{"time": 17.0, "kind": "normal"},
			{"time": 21.0, "kind": "flag", "wave": true},
			{"time": 22.0, "kind": "normal"},
			{"time": 24.0, "kind": "normal"},
			{"time": 26.0, "kind": "normal"},
		],
	},
	{
		"id": "1-3",
		"title": "白天 1-3",
		"description": "樱桃炸弹可以瞬间清掉一片僵尸。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb"],
		"unlock_plant": "wallnut",
		"start_sun": 100,
		"row_count": 3,
		"time_scale": 1.3,
		"sky_sun_range": Vector2(5.4, 6.8),
		"node_pos": Vector2(486.0, 618.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 9.0, "kind": "normal"},
			{"time": 13.0, "kind": "normal"},
			{"time": 17.0, "kind": "normal"},
			{"time": 20.0, "kind": "flag", "wave": true},
			{"time": 21.0, "kind": "normal"},
			{"time": 23.0, "kind": "normal"},
			{"time": 28.0, "kind": "normal"},
			{"time": 32.0, "kind": "flag", "wave": true},
			{"time": 33.0, "kind": "normal"},
			{"time": 34.0, "kind": "normal"},
		],
	},
	{
		"id": "1-4",
		"title": "白天 1-4",
		"description": "坚果墙能为后排争取更多输出时间。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut"],
		"unlock_plant": "potato_mine",
		"start_sun": 125,
		"row_count": 4,
		"time_scale": 1.2,
		"sky_sun_range": Vector2(5.8, 7.2),
		"node_pos": Vector2(662.0, 646.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 9.0, "kind": "normal"},
			{"time": 13.0, "kind": "normal"},
			{"time": 17.0, "kind": "normal"},
			{"time": 21.0, "kind": "normal"},
			{"time": 24.0, "kind": "flag", "wave": true},
			{"time": 25.0, "kind": "normal"},
			{"time": 27.0, "kind": "normal"},
			{"time": 31.0, "kind": "normal"},
			{"time": 36.0, "kind": "flag", "wave": true},
			{"time": 37.0, "kind": "normal"},
			{"time": 38.0, "kind": "normal"},
		],
	},
	{
		"id": "1-5",
		"title": "白天 1-5",
		"description": "路障僵尸登场，土豆地雷也能开始埋了。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine"],
		"unlock_plant": "snow_pea",
		"start_sun": 150,
		"row_count": 5,
		"time_scale": 1.15,
		"sky_sun_range": Vector2(6.2, 7.6),
		"node_pos": Vector2(818.0, 612.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 8.0, "kind": "normal"},
			{"time": 12.0, "kind": "conehead"},
			{"time": 15.0, "kind": "normal"},
			{"time": 19.0, "kind": "normal"},
			{"time": 22.0, "kind": "flag", "wave": true},
			{"time": 22.6, "kind": "normal"},
			{"time": 23.2, "kind": "conehead"},
			{"time": 24.0, "kind": "normal"},
			{"time": 29.0, "kind": "conehead"},
			{"time": 33.0, "kind": "normal"},
			{"time": 38.0, "kind": "flag", "wave": true},
			{"time": 38.5, "kind": "conehead"},
			{"time": 39.3, "kind": "normal"},
			{"time": 40.0, "kind": "normal"},
		],
	},
	{
		"id": "1-6",
		"title": "白天 1-6",
		"description": "寒冰射手能稳定减速整条路线的僵尸。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea"],
		"unlock_plant": "chomper",
		"start_sun": 175,
		"row_count": 5,
		"time_scale": 1.1,
		"sky_sun_range": Vector2(6.6, 8.0),
		"node_pos": Vector2(982.0, 640.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 8.0, "kind": "conehead"},
			{"time": 12.0, "kind": "normal"},
			{"time": 15.0, "kind": "normal"},
			{"time": 19.0, "kind": "conehead"},
			{"time": 22.0, "kind": "flag", "wave": true},
			{"time": 22.5, "kind": "normal"},
			{"time": 23.0, "kind": "conehead"},
			{"time": 24.0, "kind": "normal"},
			{"time": 29.0, "kind": "conehead"},
			{"time": 34.0, "kind": "normal"},
			{"time": 39.0, "kind": "conehead"},
			{"time": 44.0, "kind": "flag", "wave": true},
			{"time": 44.5, "kind": "conehead"},
			{"time": 45.2, "kind": "normal"},
			{"time": 46.0, "kind": "conehead"},
		],
	},
	{
		"id": "1-7",
		"title": "白天 1-7",
		"description": "撑杆跳僵尸会越过第一棵植物，大嘴花在近身时很强。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper"],
		"unlock_plant": "repeater",
		"start_sun": 200,
		"row_count": 5,
		"time_scale": 1.08,
		"sky_sun_range": Vector2(6.8, 8.2),
		"node_pos": Vector2(1128.0, 604.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 8.0, "kind": "conehead"},
			{"time": 11.0, "kind": "pole_vault"},
			{"time": 15.0, "kind": "normal"},
			{"time": 19.0, "kind": "conehead"},
			{"time": 22.0, "kind": "flag", "wave": true},
			{"time": 22.6, "kind": "pole_vault"},
			{"time": 23.2, "kind": "normal"},
			{"time": 24.0, "kind": "conehead"},
			{"time": 29.0, "kind": "pole_vault"},
			{"time": 34.0, "kind": "conehead"},
			{"time": 39.0, "kind": "normal"},
			{"time": 46.0, "kind": "flag", "wave": true},
			{"time": 46.4, "kind": "pole_vault"},
			{"time": 47.0, "kind": "conehead"},
			{"time": 47.6, "kind": "normal"},
		],
	},
	{
		"id": "1-8",
		"title": "白天 1-8",
		"description": "铁桶僵尸加入战场，双发射手也会解锁。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater"],
		"unlock_plant": "",
		"start_sun": 200,
		"row_count": 5,
		"time_scale": 1.08,
		"sky_sun_range": Vector2(7.0, 8.4),
		"node_pos": Vector2(1092.0, 476.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 8.0, "kind": "conehead"},
			{"time": 10.0, "kind": "pole_vault"},
			{"time": 14.0, "kind": "buckethead"},
			{"time": 18.0, "kind": "conehead"},
			{"time": 22.0, "kind": "flag", "wave": true},
			{"time": 22.4, "kind": "pole_vault"},
			{"time": 23.0, "kind": "normal"},
			{"time": 25.0, "kind": "buckethead"},
			{"time": 30.0, "kind": "conehead"},
			{"time": 35.0, "kind": "pole_vault"},
			{"time": 40.0, "kind": "buckethead"},
			{"time": 45.0, "kind": "conehead"},
			{"time": 52.0, "kind": "flag", "wave": true},
			{"time": 52.4, "kind": "buckethead"},
			{"time": 53.0, "kind": "pole_vault"},
			{"time": 53.8, "kind": "conehead"},
			{"time": 54.4, "kind": "normal"},
		],
	},
	{
		"id": "1-9",
		"title": "白天 1-9",
		"description": "坚果保龄球关卡，传送带会不断送来坚果。",
		"available_plants": ["wallnut_bowling"],
		"conveyor_plants": ["wallnut_bowling"],
		"unlock_plant": "amber_shooter",
		"mode": "bowling",
		"start_sun": 0,
		"row_count": 5,
		"time_scale": 1.0,
		"sky_sun_range": Vector2(99.0, 99.0),
		"node_pos": Vector2(934.0, 514.0),
		"events": [
			{"time": 4.0, "kind": "normal"},
			{"time": 6.0, "kind": "normal"},
			{"time": 9.0, "kind": "conehead"},
			{"time": 12.0, "kind": "normal"},
			{"time": 15.0, "kind": "buckethead"},
			{"time": 19.0, "kind": "flag", "wave": true},
			{"time": 19.5, "kind": "conehead"},
			{"time": 20.2, "kind": "normal"},
			{"time": 22.0, "kind": "buckethead"},
			{"time": 26.0, "kind": "conehead"},
			{"time": 30.0, "kind": "buckethead"},
			{"time": 34.0, "kind": "flag", "wave": true},
			{"time": 34.4, "kind": "buckethead"},
			{"time": 35.0, "kind": "conehead"},
			{"time": 35.8, "kind": "normal"},
		],
	},
	{
		"id": "1-10",
		"title": "白天 1-10",
		"description": "传送带第一次登场，卡片会自动送到手边。",
		"available_plants": ["peashooter", "wallnut", "potato_mine", "amber_shooter"],
		"conveyor_plants": ["peashooter", "wallnut", "potato_mine", "amber_shooter"],
		"unlock_plant": "vine_lasher",
		"mode": "conveyor",
		"start_sun": 0,
		"row_count": 5,
		"time_scale": 1.0,
		"sky_sun_range": Vector2(99.0, 99.0),
		"node_pos": Vector2(792.0, 472.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 8.0, "kind": "conehead"},
			{"time": 12.0, "kind": "buckethead"},
			{"time": 16.0, "kind": "normal"},
			{"time": 20.0, "kind": "flag", "wave": true},
			{"time": 20.6, "kind": "conehead"},
			{"time": 21.3, "kind": "normal"},
			{"time": 23.0, "kind": "buckethead"},
			{"time": 27.0, "kind": "conehead"},
			{"time": 32.0, "kind": "buckethead"},
			{"time": 37.0, "kind": "flag", "wave": true},
			{"time": 37.6, "kind": "buckethead"},
			{"time": 38.2, "kind": "conehead"},
			{"time": 39.0, "kind": "normal"},
		],
	},
	{
		"id": "1-11",
		"title": "白天 1-11",
		"description": "农夫僵尸会一路抛洒杂草，卡住你的火力线。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher"],
		"unlock_plant": "pepper_mortar",
		"start_sun": 200,
		"row_count": 5,
		"time_scale": 1.0,
		"sky_sun_range": Vector2(6.8, 8.0),
		"node_pos": Vector2(636.0, 514.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 8.0, "kind": "farmer"},
			{"time": 12.0, "kind": "conehead"},
			{"time": 16.0, "kind": "normal"},
			{"time": 20.0, "kind": "farmer"},
			{"time": 24.0, "kind": "flag", "wave": true},
			{"time": 24.6, "kind": "conehead"},
			{"time": 25.2, "kind": "farmer"},
			{"time": 26.0, "kind": "buckethead"},
			{"time": 31.0, "kind": "farmer"},
			{"time": 36.0, "kind": "buckethead"},
			{"time": 42.0, "kind": "flag", "wave": true},
			{"time": 42.6, "kind": "farmer"},
			{"time": 43.1, "kind": "buckethead"},
			{"time": 44.0, "kind": "conehead"},
		],
	},
	{
		"id": "1-12",
		"title": "白天 1-12",
		"description": "长矛僵尸死后会留下埋伏，需要继续清理。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar"],
		"unlock_plant": "cactus_guard",
		"start_sun": 225,
		"row_count": 5,
		"time_scale": 0.98,
		"sky_sun_range": Vector2(6.8, 8.0),
		"node_pos": Vector2(468.0, 484.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 8.0, "kind": "spear"},
			{"time": 11.0, "kind": "conehead"},
			{"time": 15.0, "kind": "spear"},
			{"time": 19.0, "kind": "buckethead"},
			{"time": 23.0, "kind": "flag", "wave": true},
			{"time": 23.7, "kind": "spear"},
			{"time": 24.2, "kind": "normal"},
			{"time": 25.0, "kind": "buckethead"},
			{"time": 30.0, "kind": "spear"},
			{"time": 35.0, "kind": "conehead"},
			{"time": 40.0, "kind": "flag", "wave": true},
			{"time": 40.4, "kind": "buckethead"},
			{"time": 41.0, "kind": "spear"},
			{"time": 41.8, "kind": "normal"},
		],
	},
	{
		"id": "1-13",
		"title": "白天 1-13",
		"description": "功夫僵尸会周期性发动气功，反弹豌豆。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard"],
		"unlock_plant": "pulse_bulb",
		"start_sun": 250,
		"row_count": 5,
		"time_scale": 0.96,
		"sky_sun_range": Vector2(6.8, 8.0),
		"node_pos": Vector2(298.0, 522.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 8.0, "kind": "kungfu"},
			{"time": 12.0, "kind": "conehead"},
			{"time": 16.0, "kind": "kungfu"},
			{"time": 20.0, "kind": "buckethead"},
			{"time": 24.0, "kind": "flag", "wave": true},
			{"time": 24.6, "kind": "kungfu"},
			{"time": 25.2, "kind": "conehead"},
			{"time": 26.0, "kind": "buckethead"},
			{"time": 31.0, "kind": "kungfu"},
			{"time": 36.0, "kind": "buckethead"},
			{"time": 42.0, "kind": "flag", "wave": true},
			{"time": 42.5, "kind": "kungfu"},
			{"time": 43.1, "kind": "buckethead"},
			{"time": 44.0, "kind": "conehead"},
		],
	},
	{
		"id": "1-14",
		"title": "白天 1-14",
		"description": "三种新僵尸开始混编登场，考验控场与拆障碍能力。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb"],
		"unlock_plant": "sun_bean",
		"start_sun": 275,
		"row_count": 5,
		"time_scale": 0.94,
		"sky_sun_range": Vector2(6.8, 8.0),
		"node_pos": Vector2(338.0, 364.0),
		"events": [
			{"time": 5.0, "kind": "farmer"},
			{"time": 8.0, "kind": "spear"},
			{"time": 11.0, "kind": "kungfu"},
			{"time": 15.0, "kind": "buckethead"},
			{"time": 19.0, "kind": "conehead"},
			{"time": 24.0, "kind": "flag", "wave": true},
			{"time": 24.6, "kind": "farmer"},
			{"time": 25.0, "kind": "kungfu"},
			{"time": 26.0, "kind": "buckethead"},
			{"time": 31.0, "kind": "spear"},
			{"time": 36.0, "kind": "farmer"},
			{"time": 42.0, "kind": "flag", "wave": true},
			{"time": 42.4, "kind": "buckethead"},
			{"time": 43.1, "kind": "kungfu"},
			{"time": 44.0, "kind": "spear"},
		],
	},
	{
		"id": "1-15",
		"title": "白天 1-15",
		"description": "战线拉长，混编僵尸与重装僵尸同时逼近。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean"],
		"unlock_plant": "wind_orchid",
		"start_sun": 300,
		"row_count": 5,
		"time_scale": 0.92,
		"sky_sun_range": Vector2(6.8, 8.0),
		"node_pos": Vector2(512.0, 336.0),
		"events": [
			{"time": 5.0, "kind": "farmer"},
			{"time": 8.0, "kind": "buckethead"},
			{"time": 11.0, "kind": "kungfu"},
			{"time": 14.0, "kind": "spear"},
			{"time": 18.0, "kind": "buckethead"},
			{"time": 22.0, "kind": "flag", "wave": true},
			{"time": 22.6, "kind": "farmer"},
			{"time": 23.0, "kind": "kungfu"},
			{"time": 24.0, "kind": "buckethead"},
			{"time": 28.0, "kind": "spear"},
			{"time": 33.0, "kind": "buckethead"},
			{"time": 38.0, "kind": "farmer"},
			{"time": 45.0, "kind": "flag", "wave": true},
			{"time": 45.4, "kind": "buckethead"},
			{"time": 46.0, "kind": "kungfu"},
			{"time": 46.8, "kind": "spear"},
		],
	},
	{
		"id": "1-16",
		"title": "白天 1-16",
		"description": "Boss 关卡，传送带会不断送来植物，昼光机甲会召唤援军。",
		"available_plants": ["wallnut", "potato_mine", "snow_pea", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "wind_orchid"],
		"conveyor_plants": ["wallnut", "potato_mine", "snow_pea", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "wind_orchid"],
		"unlock_plant": "puff_shroom",
		"mode": "conveyor",
		"boss_level": true,
		"start_sun": 0,
		"row_count": 5,
		"time_scale": 0.88,
		"sky_sun_range": Vector2(99.0, 99.0),
		"node_pos": Vector2(714.0, 378.0),
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 8.0, "kind": "farmer"},
			{"time": 11.0, "kind": "spear"},
			{"time": 14.0, "kind": "kungfu"},
			{"time": 18.0, "kind": "buckethead"},
			{"time": 22.0, "kind": "flag", "wave": true},
			{"time": 22.6, "kind": "farmer"},
			{"time": 23.1, "kind": "spear"},
			{"time": 24.0, "kind": "buckethead"},
			{"time": 29.0, "kind": "kungfu"},
			{"time": 34.0, "kind": "day_boss", "wave": true},
			{"time": 35.2, "kind": "buckethead"},
			{"time": 36.0, "kind": "farmer"},
			{"time": 40.0, "kind": "spear"},
			{"time": 46.0, "kind": "kungfu"},
			{"time": 52.0, "kind": "flag", "wave": true},
			{"time": 52.6, "kind": "buckethead"},
			{"time": 53.0, "kind": "farmer"},
			{"time": 54.0, "kind": "spear"},
		],
	},
	{
		"id": "2-1",
		"title": "夜晚 2-1",
		"description": "夜晚不会掉落天空阳光，小喷菇适合低成本守线。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean", "wind_orchid", "puff_shroom"],
		"unlock_plant": "sun_shroom",
		"start_sun": 50,
		"row_count": 5,
		"time_scale": 1.0,
		"sky_sun_range": Vector2(999.0, 999.0),
		"node_pos": Vector2(170.0, 628.0),
		"events": [
			{"time": 6.0, "kind": "normal"},
			{"time": 10.0, "kind": "conehead"},
			{"time": 15.0, "kind": "newspaper"},
			{"time": 20.0, "kind": "normal"},
			{"time": 25.0, "kind": "flag", "wave": true},
			{"time": 26.0, "kind": "newspaper"},
			{"time": 31.0, "kind": "conehead"},
		],
	},
	{
		"id": "2-2",
		"title": "夜晚 2-2",
		"description": "阳光菇会先产小阳光，长大后产出更多。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean", "wind_orchid", "puff_shroom", "sun_shroom"],
		"unlock_plant": "fume_shroom",
		"start_sun": 75,
		"row_count": 5,
		"time_scale": 0.98,
		"sky_sun_range": Vector2(999.0, 999.0),
		"node_pos": Vector2(332.0, 648.0),
		"events": [
			{"time": 6.0, "kind": "normal"},
			{"time": 10.0, "kind": "newspaper"},
			{"time": 14.0, "kind": "conehead"},
			{"time": 18.0, "kind": "screen_door"},
			{"time": 24.0, "kind": "flag", "wave": true},
			{"time": 25.0, "kind": "newspaper"},
			{"time": 30.0, "kind": "screen_door"},
		],
	},
	{
		"id": "2-3",
		"title": "夜晚 2-3",
		"description": "大喷菇能稳定扫穿一条前方走廊。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean", "wind_orchid", "puff_shroom", "sun_shroom", "fume_shroom"],
		"unlock_plant": "grave_buster",
		"start_sun": 100,
		"row_count": 5,
		"time_scale": 0.96,
		"sky_sun_range": Vector2(999.0, 999.0),
		"node_pos": Vector2(496.0, 620.0),
		"events": [
			{"time": 6.0, "kind": "newspaper"},
			{"time": 10.0, "kind": "screen_door"},
			{"time": 15.0, "kind": "buckethead"},
			{"time": 21.0, "kind": "newspaper"},
			{"time": 26.0, "kind": "flag", "wave": true},
			{"time": 27.0, "kind": "screen_door"},
			{"time": 32.0, "kind": "buckethead"},
		],
	},
	{
		"id": "2-4",
		"title": "夜晚 2-4",
		"description": "草坪出现坟墓，坟墓吞噬者可以直接处理它们。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean", "wind_orchid", "puff_shroom", "sun_shroom", "fume_shroom", "grave_buster"],
		"unlock_plant": "hypno_shroom",
		"start_sun": 125,
		"row_count": 5,
		"time_scale": 0.95,
		"sky_sun_range": Vector2(999.0, 999.0),
		"node_pos": Vector2(662.0, 646.0),
		"events": [
			{"time": 6.0, "kind": "newspaper"},
			{"time": 9.0, "kind": "screen_door"},
			{"time": 14.0, "kind": "football"},
			{"time": 20.0, "kind": "newspaper"},
			{"time": 25.0, "kind": "flag", "wave": true},
			{"time": 26.0, "kind": "football"},
			{"time": 31.0, "kind": "screen_door"},
		],
	},
	{
		"id": "2-5",
		"title": "夜晚 2-5",
		"description": "魅惑菇适合把高威胁单位直接变成内鬼。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean", "wind_orchid", "puff_shroom", "sun_shroom", "fume_shroom", "grave_buster", "hypno_shroom"],
		"unlock_plant": "scaredy_shroom",
		"start_sun": 150,
		"row_count": 5,
		"time_scale": 0.94,
		"sky_sun_range": Vector2(999.0, 999.0),
		"node_pos": Vector2(822.0, 614.0),
		"events": [
			{"time": 6.0, "kind": "screen_door"},
			{"time": 10.0, "kind": "football"},
			{"time": 14.0, "kind": "newspaper"},
			{"time": 18.0, "kind": "buckethead"},
			{"time": 24.0, "kind": "flag", "wave": true},
			{"time": 25.0, "kind": "football"},
			{"time": 30.0, "kind": "screen_door"},
		],
	},
	{
		"id": "2-6",
		"title": "夜晚 2-6",
		"description": "胆小菇火力很足，但前线靠得太近就会躲起来。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean", "wind_orchid", "puff_shroom", "sun_shroom", "fume_shroom", "grave_buster", "hypno_shroom", "scaredy_shroom"],
		"unlock_plant": "ice_shroom",
		"start_sun": 175,
		"row_count": 5,
		"time_scale": 0.92,
		"sky_sun_range": Vector2(999.0, 999.0),
		"node_pos": Vector2(986.0, 642.0),
		"events": [
			{"time": 6.0, "kind": "screen_door"},
			{"time": 10.0, "kind": "football"},
			{"time": 14.0, "kind": "newspaper"},
			{"time": 18.0, "kind": "dancing"},
			{"time": 24.0, "kind": "flag", "wave": true},
			{"time": 25.0, "kind": "football"},
			{"time": 31.0, "kind": "dancing"},
		],
	},
	{
		"id": "2-7",
		"title": "夜晚 2-7",
		"description": "寒冰菇可以冻结整场，为夜晚重压争取时间。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean", "wind_orchid", "puff_shroom", "sun_shroom", "fume_shroom", "grave_buster", "hypno_shroom", "scaredy_shroom", "ice_shroom"],
		"unlock_plant": "doom_shroom",
		"start_sun": 200,
		"row_count": 5,
		"time_scale": 0.9,
		"sky_sun_range": Vector2(999.0, 999.0),
		"node_pos": Vector2(1118.0, 604.0),
		"events": [
			{"time": 6.0, "kind": "football"},
			{"time": 11.0, "kind": "dancing"},
			{"time": 15.0, "kind": "buckethead"},
			{"time": 20.0, "kind": "screen_door"},
			{"time": 26.0, "kind": "flag", "wave": true},
			{"time": 27.0, "kind": "football"},
			{"time": 32.0, "kind": "dancing"},
		],
	},
	{
		"id": "2-8",
		"title": "夜晚 2-8",
		"description": "毁灭菇登场，夜晚世界进入大规模清场阶段。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean", "wind_orchid", "puff_shroom", "sun_shroom", "fume_shroom", "grave_buster", "hypno_shroom", "scaredy_shroom", "ice_shroom", "doom_shroom"],
		"unlock_plant": "",
		"start_sun": 225,
		"row_count": 5,
		"time_scale": 0.88,
		"sky_sun_range": Vector2(999.0, 999.0),
		"node_pos": Vector2(1138.0, 470.0),
		"events": [
			{"time": 6.0, "kind": "football"},
			{"time": 10.0, "kind": "dancing"},
			{"time": 14.0, "kind": "screen_door"},
			{"time": 18.0, "kind": "buckethead"},
			{"time": 22.0, "kind": "newspaper"},
			{"time": 28.0, "kind": "flag", "wave": true},
			{"time": 29.0, "kind": "football"},
			{"time": 33.0, "kind": "dancing"},
			{"time": 38.0, "kind": "screen_door"},
		],
	},
	{
		"id": "2-9",
		"title": "夜晚 2-9",
		"description": "锤僵尸关卡，点击僵尸挥锤，攒出 75 阳光后再用功能牌解场。",
		"available_plants": ["grave_buster", "potato_mine", "cherry_bomb"],
		"unlock_plant": "",
		"mode": "whack",
		"start_sun": 0,
		"row_count": 5,
		"time_scale": 1.0,
		"sky_sun_range": Vector2(999.0, 999.0),
		"node_pos": Vector2(1004.0, 348.0),
		"grave_layout": [
			Vector2i(0, 4), Vector2i(0, 5), Vector2i(0, 6),
			Vector2i(1, 4), Vector2i(1, 5), Vector2i(1, 6),
			Vector2i(2, 4), Vector2i(2, 5), Vector2i(2, 6),
			Vector2i(3, 4), Vector2i(3, 5), Vector2i(3, 6),
			Vector2i(4, 4), Vector2i(4, 5), Vector2i(4, 6),
		],
		"events": [
			{"time": 4.0, "kind": "normal"},
			{"time": 6.0, "kind": "normal"},
			{"time": 8.0, "kind": "conehead"},
			{"time": 10.0, "kind": "normal", "wave": true},
			{"time": 13.0, "kind": "normal"},
			{"time": 16.0, "kind": "conehead"},
			{"time": 19.0, "kind": "buckethead"},
			{"time": 23.0, "kind": "normal", "wave": true},
			{"time": 27.0, "kind": "conehead"},
			{"time": 31.0, "kind": "buckethead"},
			{"time": 36.0, "kind": "conehead"},
			{"time": 41.0, "kind": "buckethead", "wave": true},
		],
	},
	{
		"id": "2-10",
		"title": "夜晚 2-10",
		"description": "参考原版夜晚传送带关，13 座坟墓压场，传送带会持续送来夜晚蘑菇与解场牌。",
		"available_plants": ["puff_shroom", "fume_shroom", "grave_buster", "scaredy_shroom", "ice_shroom", "doom_shroom"],
		"conveyor_plants": ["puff_shroom", "puff_shroom", "puff_shroom", "fume_shroom", "fume_shroom", "grave_buster", "grave_buster", "grave_buster", "scaredy_shroom", "ice_shroom", "doom_shroom"],
		"unlock_plant": "",
		"mode": "conveyor",
		"start_sun": 0,
		"row_count": 5,
		"time_scale": 1.02,
		"sky_sun_range": Vector2(999.0, 999.0),
		"node_pos": Vector2(822.0, 292.0),
		"grave_layout": [
			Vector2i(0, 3), Vector2i(0, 5), Vector2i(0, 7),
			Vector2i(1, 2), Vector2i(1, 4), Vector2i(1, 6),
			Vector2i(2, 3), Vector2i(2, 5),
			Vector2i(3, 2), Vector2i(3, 4), Vector2i(3, 7),
			Vector2i(4, 3), Vector2i(4, 6),
		],
		"events": [
			{"time": 5.0, "kind": "normal"},
			{"time": 7.0, "kind": "normal"},
			{"time": 9.0, "kind": "conehead"},
			{"time": 12.0, "kind": "screen_door"},
			{"time": 15.0, "kind": "normal"},
			{"time": 19.0, "kind": "flag", "wave": true},
			{"time": 22.0, "kind": "conehead"},
			{"time": 25.0, "kind": "screen_door"},
			{"time": 28.0, "kind": "buckethead"},
			{"time": 32.0, "kind": "dancing"},
			{"time": 36.0, "kind": "football"},
			{"time": 41.0, "kind": "flag", "wave": true},
			{"time": 44.0, "kind": "screen_door"},
			{"time": 48.0, "kind": "buckethead"},
			{"time": 52.0, "kind": "dancing"},
			{"time": 57.0, "kind": "football"},
			{"time": 62.0, "kind": "screen_door"},
			{"time": 67.0, "kind": "buckethead"},
			{"time": 73.0, "kind": "football"},
			{"time": 79.0, "kind": "flag", "wave": true},
		],
	},
	{
		"id": "2-11",
		"title": "夜晚 2-11",
		"description": "新僵尸开始混编。月光莲能兼顾夜晚经济与叫醒周围睡着的植物。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean", "wind_orchid", "puff_shroom", "sun_shroom", "fume_shroom", "grave_buster", "hypno_shroom", "scaredy_shroom", "ice_shroom", "doom_shroom", "moon_lotus"],
		"unlock_plant": "prism_grass",
		"start_sun": 200,
		"row_count": 5,
		"time_scale": 0.9,
		"sky_sun_range": Vector2(999.0, 999.0),
		"node_pos": Vector2(674.0, 214.0),
		"events": [
			{"time": 5.0, "kind": "ninja"},
			{"time": 8.0, "kind": "screen_door"},
			{"time": 11.0, "kind": "conehead"},
			{"time": 15.0, "kind": "nether"},
			{"time": 20.0, "kind": "flag", "wave": true},
			{"time": 23.0, "kind": "ninja"},
			{"time": 27.0, "kind": "basketball"},
			{"time": 31.0, "kind": "screen_door"},
			{"time": 35.0, "kind": "nether"},
			{"time": 40.0, "kind": "flag", "wave": true},
			{"time": 44.0, "kind": "basketball"},
			{"time": 49.0, "kind": "ninja"},
			{"time": 54.0, "kind": "buckethead"},
			{"time": 59.0, "kind": "nether"},
			{"time": 65.0, "kind": "flag", "wave": true},
		],
	},
	{
		"id": "2-12",
		"title": "夜晚 2-12",
		"description": "棱镜草会沿直线穿透多只目标，适合收拾忍者和铁门混编。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean", "wind_orchid", "puff_shroom", "sun_shroom", "fume_shroom", "grave_buster", "hypno_shroom", "scaredy_shroom", "ice_shroom", "doom_shroom", "moon_lotus", "prism_grass"],
		"unlock_plant": "lantern_bloom",
		"start_sun": 225,
		"row_count": 5,
		"time_scale": 0.88,
		"sky_sun_range": Vector2(999.0, 999.0),
		"node_pos": Vector2(484.0, 248.0),
		"events": [
			{"time": 5.0, "kind": "screen_door"},
			{"time": 9.0, "kind": "ninja"},
			{"time": 12.0, "kind": "basketball"},
			{"time": 16.0, "kind": "nether"},
			{"time": 21.0, "kind": "flag", "wave": true},
			{"time": 25.0, "kind": "buckethead"},
			{"time": 29.0, "kind": "ninja"},
			{"time": 34.0, "kind": "basketball"},
			{"time": 39.0, "kind": "screen_door"},
			{"time": 44.0, "kind": "flag", "wave": true},
			{"time": 48.0, "kind": "basketball"},
			{"time": 52.0, "kind": "ninja"},
			{"time": 57.0, "kind": "football"},
			{"time": 63.0, "kind": "nether"},
			{"time": 70.0, "kind": "flag", "wave": true},
		],
	},
	{
		"id": "2-13",
		"title": "夜晚 2-13",
		"description": "提灯花能照醒附近植物，并把从墓碑钻出的冥界僵尸压回去。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean", "wind_orchid", "puff_shroom", "sun_shroom", "fume_shroom", "grave_buster", "hypno_shroom", "scaredy_shroom", "ice_shroom", "doom_shroom", "moon_lotus", "prism_grass", "lantern_bloom"],
		"unlock_plant": "meteor_gourd",
		"start_sun": 250,
		"row_count": 5,
		"time_scale": 0.87,
		"sky_sun_range": Vector2(999.0, 999.0),
		"node_pos": Vector2(326.0, 334.0),
		"events": [
			{"time": 5.0, "kind": "nether"},
			{"time": 9.0, "kind": "screen_door"},
			{"time": 13.0, "kind": "ninja"},
			{"time": 17.0, "kind": "basketball"},
			{"time": 22.0, "kind": "flag", "wave": true},
			{"time": 26.0, "kind": "nether"},
			{"time": 30.0, "kind": "buckethead"},
			{"time": 35.0, "kind": "basketball"},
			{"time": 40.0, "kind": "ninja"},
			{"time": 46.0, "kind": "flag", "wave": true},
			{"time": 50.0, "kind": "football"},
			{"time": 55.0, "kind": "nether"},
			{"time": 60.0, "kind": "screen_door"},
			{"time": 66.0, "kind": "basketball"},
			{"time": 73.0, "kind": "flag", "wave": true},
		],
	},
	{
		"id": "2-14",
		"title": "夜晚 2-14",
		"description": "哪吒僵尸会直接扑向中后排。陨星葫芦可以远程砸落解场。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean", "wind_orchid", "puff_shroom", "sun_shroom", "fume_shroom", "grave_buster", "hypno_shroom", "scaredy_shroom", "ice_shroom", "doom_shroom", "moon_lotus", "prism_grass", "lantern_bloom", "meteor_gourd"],
		"unlock_plant": "root_snare",
		"start_sun": 275,
		"row_count": 5,
		"time_scale": 0.86,
		"sky_sun_range": Vector2(999.0, 999.0),
		"node_pos": Vector2(248.0, 472.0),
		"events": [
			{"time": 5.0, "kind": "nezha"},
			{"time": 9.0, "kind": "ninja"},
			{"time": 13.0, "kind": "screen_door"},
			{"time": 18.0, "kind": "basketball"},
			{"time": 23.0, "kind": "flag", "wave": true},
			{"time": 27.0, "kind": "nezha"},
			{"time": 31.0, "kind": "nether"},
			{"time": 36.0, "kind": "buckethead"},
			{"time": 41.0, "kind": "ninja"},
			{"time": 47.0, "kind": "flag", "wave": true},
			{"time": 51.0, "kind": "football"},
			{"time": 56.0, "kind": "nezha"},
			{"time": 62.0, "kind": "basketball"},
			{"time": 69.0, "kind": "nether"},
			{"time": 77.0, "kind": "flag", "wave": true},
		],
	},
	{
		"id": "2-15",
		"title": "夜晚 2-15",
		"description": "缠根草可以拦住高速突脸单位，特别适合处理忍者和哪吒混冲。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean", "wind_orchid", "puff_shroom", "sun_shroom", "fume_shroom", "grave_buster", "hypno_shroom", "scaredy_shroom", "ice_shroom", "doom_shroom", "moon_lotus", "prism_grass", "lantern_bloom", "meteor_gourd", "root_snare"],
		"unlock_plant": "thunder_pine",
		"start_sun": 300,
		"row_count": 5,
		"time_scale": 0.84,
		"sky_sun_range": Vector2(999.0, 999.0),
		"node_pos": Vector2(402.0, 596.0),
		"events": [
			{"time": 5.0, "kind": "ninja"},
			{"time": 9.0, "kind": "nezha"},
			{"time": 13.0, "kind": "basketball"},
			{"time": 17.0, "kind": "screen_door"},
			{"time": 22.0, "kind": "flag", "wave": true},
			{"time": 26.0, "kind": "ninja"},
			{"time": 31.0, "kind": "nether"},
			{"time": 36.0, "kind": "football"},
			{"time": 41.0, "kind": "nezha"},
			{"time": 47.0, "kind": "flag", "wave": true},
			{"time": 51.0, "kind": "buckethead"},
			{"time": 56.0, "kind": "basketball"},
			{"time": 62.0, "kind": "ninja"},
			{"time": 68.0, "kind": "nether"},
			{"time": 76.0, "kind": "flag", "wave": true},
		],
	},
	{
		"id": "2-16",
		"title": "夜晚 2-16",
		"description": "雷松会把电流连到相邻目标，是夜晚后段对付多路压境的关键。",
		"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean", "wind_orchid", "puff_shroom", "sun_shroom", "fume_shroom", "grave_buster", "hypno_shroom", "scaredy_shroom", "ice_shroom", "doom_shroom", "moon_lotus", "prism_grass", "lantern_bloom", "meteor_gourd", "root_snare", "thunder_pine"],
		"unlock_plant": "dream_drum",
		"start_sun": 325,
		"row_count": 5,
		"time_scale": 0.82,
		"sky_sun_range": Vector2(999.0, 999.0),
		"node_pos": Vector2(620.0, 554.0),
		"events": [
			{"time": 5.0, "kind": "basketball"},
			{"time": 9.0, "kind": "nether"},
			{"time": 13.0, "kind": "nezha"},
			{"time": 18.0, "kind": "football"},
			{"time": 23.0, "kind": "flag", "wave": true},
			{"time": 27.0, "kind": "ninja"},
			{"time": 32.0, "kind": "screen_door"},
			{"time": 37.0, "kind": "basketball"},
			{"time": 42.0, "kind": "nether"},
			{"time": 48.0, "kind": "flag", "wave": true},
			{"time": 52.0, "kind": "buckethead"},
			{"time": 57.0, "kind": "nezha"},
			{"time": 63.0, "kind": "dark_football"},
			{"time": 69.0, "kind": "ninja"},
			{"time": 77.0, "kind": "flag", "wave": true},
		],
	},
		{
			"id": "2-17",
			"title": "夜晚 2-17",
			"description": "夜晚传送带 Boss 关，暗夜尸王会召夜行援军、升坟墓并压制植物入睡。",
			"boss_level": true,
			"mode": "conveyor",
			"available_plants": ["puff_shroom", "fume_shroom", "grave_buster", "hypno_shroom", "scaredy_shroom", "ice_shroom", "doom_shroom", "prism_grass", "lantern_bloom", "meteor_gourd", "root_snare", "thunder_pine", "dream_drum", "wallnut", "snow_pea", "wind_orchid"],
			"conveyor_plants": ["puff_shroom", "puff_shroom", "fume_shroom", "fume_shroom", "grave_buster", "grave_buster", "hypno_shroom", "scaredy_shroom", "ice_shroom", "doom_shroom", "prism_grass", "lantern_bloom", "meteor_gourd", "root_snare", "thunder_pine", "dream_drum", "wallnut", "snow_pea", "wind_orchid"],
			"unlock_plant": "lily_pad",
			"start_sun": 0,
			"row_count": 5,
			"time_scale": 0.84,
			"sky_sun_range": Vector2(999.0, 999.0),
			"node_pos": Vector2(804.0, 444.0),
			"grave_layout": [
				Vector2i(0, 2), Vector2i(0, 5), Vector2i(0, 7),
				Vector2i(1, 3), Vector2i(1, 6),
				Vector2i(2, 2), Vector2i(2, 4), Vector2i(2, 7),
				Vector2i(3, 3), Vector2i(3, 6),
				Vector2i(4, 2), Vector2i(4, 5), Vector2i(4, 7),
			],
			"events": [
				{"time": 5.0, "kind": "nether"},
				{"time": 8.0, "kind": "basketball"},
				{"time": 12.0, "kind": "ninja"},
				{"time": 16.0, "kind": "nezha"},
				{"time": 20.0, "kind": "screen_door"},
				{"time": 25.0, "kind": "flag", "wave": true},
				{"time": 29.0, "kind": "football"},
				{"time": 33.0, "kind": "dark_football"},
				{"time": 37.0, "kind": "nether"},
				{"time": 42.0, "kind": "night_boss", "wave": true},
				{"time": 43.0, "kind": "basketball"},
				{"time": 47.0, "kind": "ninja"},
				{"time": 53.0, "kind": "flag", "wave": true},
				{"time": 57.0, "kind": "buckethead"},
				{"time": 61.0, "kind": "nezha"},
				{"time": 66.0, "kind": "dark_football"},
				{"time": 72.0, "kind": "nether"},
				{"time": 79.0, "kind": "flag", "wave": true},
			],
		},
		{
			"id": "3-1",
			"title": "泳池时代 3-1",
			"description": "白天泳池开放，中央两路需要睡莲或水生植物才能稳定布阵。",
			"terrain": "pool",
			"water_rows": [2, 3],
			"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean", "wind_orchid", "puff_shroom", "sun_shroom", "fume_shroom", "grave_buster", "hypno_shroom", "scaredy_shroom", "ice_shroom", "doom_shroom", "moon_lotus", "prism_grass", "lantern_bloom", "meteor_gourd", "root_snare", "thunder_pine", "dream_drum", "lily_pad"],
			"unlock_plant": "squash",
			"start_sun": 175,
			"row_count": 6,
			"time_scale": 0.92,
			"sky_sun_range": Vector2(6.8, 8.0),
			"node_pos": Vector2(174.0, 626.0),
			"events": [
				{"time": 5.0, "kind": "normal"},
				{"time": 9.0, "kind": "lifebuoy_normal", "row": 2},
				{"time": 13.0, "kind": "normal"},
				{"time": 17.0, "kind": "lifebuoy_normal", "row": 3},
				{"time": 21.0, "kind": "conehead"},
				{"time": 25.0, "kind": "flag", "wave": true},
				{"time": 30.0, "kind": "lifebuoy_normal", "row": 2},
				{"time": 35.0, "kind": "conehead", "row": 4},
				{"time": 41.0, "kind": "lifebuoy_normal", "row": 3},
				{"time": 47.0, "kind": "flag", "wave": true},
				{"time": 53.0, "kind": "conehead", "row": 1},
				{"time": 60.0, "kind": "lifebuoy_cone", "row": 2},
				{"time": 67.0, "kind": "buckethead", "row": 5},
				{"time": 75.0, "kind": "flag", "wave": true},
			],
		},
		{
			"id": "3-2",
			"title": "泳池时代 3-2",
			"description": "窝瓜能用一次重压及时补漏，潜水僵尸则会避开大多数直线火力。",
			"terrain": "pool",
			"water_rows": [2, 3],
			"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean", "wind_orchid", "puff_shroom", "sun_shroom", "fume_shroom", "grave_buster", "hypno_shroom", "scaredy_shroom", "ice_shroom", "doom_shroom", "moon_lotus", "prism_grass", "lantern_bloom", "meteor_gourd", "root_snare", "thunder_pine", "dream_drum", "lily_pad", "squash"],
			"unlock_plant": "threepeater",
			"start_sun": 200,
			"row_count": 6,
			"time_scale": 0.9,
			"sky_sun_range": Vector2(6.8, 8.0),
			"node_pos": Vector2(336.0, 648.0),
			"events": [
				{"time": 5.0, "kind": "lifebuoy_normal", "row": 2},
				{"time": 9.0, "kind": "snorkel", "row": 3},
				{"time": 13.0, "kind": "conehead"},
				{"time": 17.0, "kind": "snorkel", "row": 2},
				{"time": 21.0, "kind": "conehead", "row": 5},
				{"time": 26.0, "kind": "flag", "wave": true},
				{"time": 31.0, "kind": "snorkel", "row": 3},
				{"time": 36.0, "kind": "lifebuoy_cone", "row": 2},
				{"time": 42.0, "kind": "buckethead", "row": 0},
				{"time": 48.0, "kind": "flag", "wave": true},
				{"time": 54.0, "kind": "snorkel", "row": 2},
				{"time": 60.0, "kind": "conehead", "row": 4},
				{"time": 67.0, "kind": "lifebuoy_bucket", "row": 3},
				{"time": 75.0, "kind": "flag", "wave": true},
			],
		},
		{
			"id": "3-3",
			"title": "泳池时代 3-3",
			"description": "三线射手能照顾上下邻路，泳池里多线火力开始变得关键。",
			"terrain": "pool",
			"water_rows": [2, 3],
			"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean", "wind_orchid", "puff_shroom", "sun_shroom", "fume_shroom", "grave_buster", "hypno_shroom", "scaredy_shroom", "ice_shroom", "doom_shroom", "moon_lotus", "prism_grass", "lantern_bloom", "meteor_gourd", "root_snare", "thunder_pine", "dream_drum", "lily_pad", "squash", "threepeater"],
			"unlock_plant": "tangle_kelp",
			"start_sun": 225,
			"row_count": 6,
			"time_scale": 0.88,
			"sky_sun_range": Vector2(6.8, 8.0),
			"node_pos": Vector2(510.0, 618.0),
			"events": [
				{"time": 5.0, "kind": "lifebuoy_normal", "row": 2},
				{"time": 8.0, "kind": "lifebuoy_cone", "row": 3},
				{"time": 12.0, "kind": "snorkel", "row": 2},
				{"time": 16.0, "kind": "conehead", "row": 1},
				{"time": 21.0, "kind": "dolphin_rider", "row": 3},
				{"time": 27.0, "kind": "flag", "wave": true},
				{"time": 32.0, "kind": "snorkel", "row": 2},
				{"time": 37.0, "kind": "buckethead", "row": 4},
				{"time": 43.0, "kind": "dolphin_rider", "row": 2},
				{"time": 50.0, "kind": "flag", "wave": true},
				{"time": 56.0, "kind": "snorkel", "row": 3},
				{"time": 63.0, "kind": "conehead", "row": 5},
				{"time": 70.0, "kind": "lifebuoy_bucket", "row": 2},
				{"time": 79.0, "kind": "flag", "wave": true},
			],
		},
		{
			"id": "3-4",
			"title": "泳池时代 3-4",
			"description": "缠绕海草是水路特攻，能把贴到脸上的游泳僵尸直接拖走。",
			"terrain": "pool",
			"water_rows": [2, 3],
			"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean", "wind_orchid", "puff_shroom", "sun_shroom", "fume_shroom", "grave_buster", "hypno_shroom", "scaredy_shroom", "ice_shroom", "doom_shroom", "moon_lotus", "prism_grass", "lantern_bloom", "meteor_gourd", "root_snare", "thunder_pine", "dream_drum", "lily_pad", "squash", "threepeater", "tangle_kelp"],
			"unlock_plant": "jalapeno",
			"start_sun": 250,
			"row_count": 6,
			"time_scale": 0.86,
			"sky_sun_range": Vector2(6.8, 8.0),
			"node_pos": Vector2(686.0, 646.0),
			"events": [
				{"time": 5.0, "kind": "snorkel", "row": 2},
				{"time": 8.0, "kind": "lifebuoy_normal", "row": 3},
				{"time": 12.0, "kind": "dolphin_rider", "row": 2},
				{"time": 16.0, "kind": "farmer", "row": 0},
				{"time": 21.0, "kind": "buckethead", "row": 5},
				{"time": 27.0, "kind": "flag", "wave": true},
				{"time": 32.0, "kind": "snorkel", "row": 3},
				{"time": 38.0, "kind": "lifebuoy_cone", "row": 2},
				{"time": 44.0, "kind": "dolphin_rider", "row": 3},
				{"time": 51.0, "kind": "flag", "wave": true},
				{"time": 58.0, "kind": "kungfu", "row": 1},
				{"time": 65.0, "kind": "conehead", "row": 4},
				{"time": 73.0, "kind": "nether", "row": 5},
				{"time": 82.0, "kind": "flag", "wave": true},
			],
		},
		{
			"id": "3-5",
			"title": "泳池时代 3-5",
			"description": "火爆辣椒能横扫整路，雪橇车僵尸则会用冰道重塑草坪节奏。",
			"terrain": "pool",
			"water_rows": [2, 3],
			"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean", "wind_orchid", "puff_shroom", "sun_shroom", "fume_shroom", "grave_buster", "hypno_shroom", "scaredy_shroom", "ice_shroom", "doom_shroom", "moon_lotus", "prism_grass", "lantern_bloom", "meteor_gourd", "root_snare", "thunder_pine", "dream_drum", "lily_pad", "squash", "threepeater", "tangle_kelp", "jalapeno"],
			"unlock_plant": "spikeweed",
			"start_sun": 275,
			"row_count": 6,
			"time_scale": 0.84,
			"sky_sun_range": Vector2(6.8, 8.0),
			"node_pos": Vector2(850.0, 612.0),
			"events": [
				{"time": 5.0, "kind": "lifebuoy_normal", "row": 2},
				{"time": 9.0, "kind": "zomboni", "row": 1},
				{"time": 13.0, "kind": "snorkel", "row": 3},
				{"time": 18.0, "kind": "spear", "row": 4},
				{"time": 24.0, "kind": "flag", "wave": true},
				{"time": 29.0, "kind": "dolphin_rider", "row": 2},
				{"time": 35.0, "kind": "zomboni", "row": 3},
				{"time": 41.0, "kind": "basketball", "row": 0},
				{"time": 48.0, "kind": "flag", "wave": true},
				{"time": 55.0, "kind": "snorkel", "row": 2},
				{"time": 62.0, "kind": "farmer", "row": 4},
				{"time": 70.0, "kind": "buckethead", "row": 5},
				{"time": 79.0, "kind": "flag", "wave": true},
			],
		},
		{
			"id": "3-6",
			"title": "泳池时代 3-6",
			"description": "地刺会稳定扎穿沿路前进的目标，也是对付雪橇车的重要卡位点。",
			"terrain": "pool",
			"water_rows": [2, 3],
			"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean", "wind_orchid", "puff_shroom", "sun_shroom", "fume_shroom", "grave_buster", "hypno_shroom", "scaredy_shroom", "ice_shroom", "doom_shroom", "moon_lotus", "prism_grass", "lantern_bloom", "meteor_gourd", "root_snare", "thunder_pine", "dream_drum", "lily_pad", "squash", "threepeater", "tangle_kelp", "jalapeno", "spikeweed"],
			"unlock_plant": "torchwood",
			"start_sun": 300,
			"row_count": 6,
			"time_scale": 0.82,
			"sky_sun_range": Vector2(6.8, 8.0),
			"node_pos": Vector2(1008.0, 640.0),
			"events": [
				{"time": 5.0, "kind": "zomboni", "row": 2},
				{"time": 10.0, "kind": "snorkel", "row": 3},
				{"time": 14.0, "kind": "dolphin_rider", "row": 2},
				{"time": 19.0, "kind": "ninja", "row": 0},
				{"time": 25.0, "kind": "flag", "wave": true},
				{"time": 31.0, "kind": "bobsled_team", "row": 2},
				{"time": 37.0, "kind": "zomboni", "row": 3},
				{"time": 44.0, "kind": "basketball", "row": 4},
				{"time": 52.0, "kind": "flag", "wave": true},
				{"time": 59.0, "kind": "nether", "row": 5},
				{"time": 66.0, "kind": "bobsled_team", "row": 3},
				{"time": 74.0, "kind": "buckethead", "row": 5},
				{"time": 84.0, "kind": "flag", "wave": true},
			],
		},
		{
			"id": "3-7",
			"title": "泳池时代 3-7",
			"description": "火炬树桩开始把水面与草地两侧的弹道统一提速，混合冲锋会明显加重。",
			"terrain": "pool",
			"water_rows": [2, 3],
			"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean", "wind_orchid", "puff_shroom", "sun_shroom", "fume_shroom", "grave_buster", "hypno_shroom", "scaredy_shroom", "ice_shroom", "doom_shroom", "moon_lotus", "prism_grass", "lantern_bloom", "meteor_gourd", "root_snare", "thunder_pine", "dream_drum", "lily_pad", "squash", "threepeater", "tangle_kelp", "jalapeno", "spikeweed", "torchwood"],
			"unlock_plant": "tallnut",
			"start_sun": 325,
			"row_count": 6,
			"time_scale": 0.8,
			"sky_sun_range": Vector2(6.8, 8.0),
			"node_pos": Vector2(1156.0, 604.0),
			"events": [
				{"time": 5.0, "kind": "zomboni", "row": 1},
				{"time": 10.0, "kind": "lifebuoy_cone", "row": 2},
				{"time": 15.0, "kind": "snorkel", "row": 3},
				{"time": 20.0, "kind": "dolphin_rider", "row": 2},
				{"time": 22.0, "kind": "farmer", "row": 5},
				{"time": 26.0, "kind": "flag", "wave": true},
				{"time": 32.0, "kind": "bobsled_team", "row": 1},
				{"time": 38.0, "kind": "zomboni", "row": 3},
				{"time": 45.0, "kind": "kungfu", "row": 4},
				{"time": 53.0, "kind": "flag", "wave": true},
				{"time": 60.0, "kind": "dolphin_rider", "row": 3},
				{"time": 63.0, "kind": "nezha", "row": 0},
				{"time": 67.0, "kind": "bobsled_team", "row": 2},
				{"time": 75.0, "kind": "dark_football", "row": 5},
				{"time": 85.0, "kind": "flag", "wave": true},
			],
		},
		{
			"id": "3-8",
			"title": "泳池时代 3-8",
			"description": "高坚果压轴登场，泳池时代前段以冰道、潜水与海豚混编收束。",
			"terrain": "pool",
			"water_rows": [2, 3],
			"available_plants": ["peashooter", "sunflower", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "sun_bean", "wind_orchid", "puff_shroom", "sun_shroom", "fume_shroom", "grave_buster", "hypno_shroom", "scaredy_shroom", "ice_shroom", "doom_shroom", "moon_lotus", "prism_grass", "lantern_bloom", "meteor_gourd", "root_snare", "thunder_pine", "dream_drum", "lily_pad", "squash", "threepeater", "tangle_kelp", "jalapeno", "spikeweed", "torchwood", "tallnut"],
			"unlock_plant": "",
			"start_sun": 350,
			"row_count": 6,
			"time_scale": 0.78,
			"sky_sun_range": Vector2(6.8, 8.0),
			"node_pos": Vector2(1096.0, 470.0),
			"events": [
				{"time": 5.0, "kind": "zomboni", "row": 2},
				{"time": 10.0, "kind": "snorkel", "row": 3},
				{"time": 15.0, "kind": "dolphin_rider", "row": 2},
				{"time": 20.0, "kind": "basketball", "row": 0},
				{"time": 26.0, "kind": "flag", "wave": true},
				{"time": 32.0, "kind": "bobsled_team", "row": 2},
				{"time": 38.0, "kind": "ninja", "row": 4},
				{"time": 45.0, "kind": "dark_football", "row": 5},
				{"time": 53.0, "kind": "flag", "wave": true},
				{"time": 60.0, "kind": "nether", "row": 1},
				{"time": 67.0, "kind": "dolphin_rider", "row": 3},
				{"time": 74.0, "kind": "farmer", "row": 4},
				{"time": 82.0, "kind": "bobsled_team", "row": 3},
				{"time": 92.0, "kind": "flag", "wave": true},
			],
		},
		{
			"id": "3-9",
			"title": "泳池时代 3-9",
			"description": "泳池传送带开打，重点转向睡莲调度与水陆混编的节奏应对。",
			"terrain": "pool",
			"water_rows": [2, 3],
			"mode": "conveyor",
			"available_plants": ["peashooter", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "wind_orchid", "puff_shroom", "fume_shroom", "hypno_shroom", "scaredy_shroom", "ice_shroom", "doom_shroom", "prism_grass", "lantern_bloom", "meteor_gourd", "root_snare", "thunder_pine", "dream_drum", "lily_pad", "squash", "threepeater", "tangle_kelp", "jalapeno", "spikeweed", "torchwood", "tallnut"],
			"conveyor_plants": ["lily_pad", "lily_pad", "lily_pad", "lily_pad", "tangle_kelp", "tangle_kelp", "squash", "wallnut", "snow_pea", "repeater", "threepeater", "jalapeno", "spikeweed", "torchwood", "tallnut", "pepper_mortar", "cactus_guard", "pulse_bulb", "wind_orchid", "prism_grass", "dream_drum", "cherry_bomb", "hypno_shroom", "doom_shroom"],
			"unlock_plant": "",
			"start_sun": 0,
			"row_count": 6,
			"time_scale": 0.78,
			"sky_sun_range": Vector2(999.0, 999.0),
			"node_pos": Vector2(930.0, 338.0),
			"events": [
				{"time": 5.0, "kind": "lifebuoy_cone", "row": 2},
				{"time": 9.0, "kind": "snorkel", "row": 3},
				{"time": 14.0, "kind": "farmer", "row": 0},
				{"time": 18.0, "kind": "dolphin_rider", "row": 2},
				{"time": 24.0, "kind": "flag", "wave": true},
				{"time": 29.0, "kind": "bobsled_team", "row": 3},
				{"time": 35.0, "kind": "zomboni", "row": 1},
				{"time": 41.0, "kind": "basketball", "row": 5},
				{"time": 48.0, "kind": "flag", "wave": true},
				{"time": 53.0, "kind": "nether", "row": 4},
				{"time": 59.0, "kind": "ninja", "row": 0},
				{"time": 64.0, "kind": "lifebuoy_bucket", "row": 2},
				{"time": 70.0, "kind": "dark_football", "row": 5},
				{"time": 78.0, "kind": "kungfu", "row": 1},
				{"time": 86.0, "kind": "flag", "wave": true},
			],
		},
		{
			"id": "3-10",
			"title": "泳池时代 3-10",
			"description": "泳池传送带总压轴，截止当前出现过的全部非 Boss 僵尸都会混进四波攻势。",
			"terrain": "pool",
			"water_rows": [2, 3],
			"mode": "conveyor",
			"available_plants": ["peashooter", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "wind_orchid", "puff_shroom", "fume_shroom", "hypno_shroom", "scaredy_shroom", "ice_shroom", "doom_shroom", "prism_grass", "lantern_bloom", "meteor_gourd", "root_snare", "thunder_pine", "dream_drum", "lily_pad", "squash", "threepeater", "tangle_kelp", "jalapeno", "spikeweed", "torchwood", "tallnut"],
			"conveyor_plants": ["lily_pad", "lily_pad", "lily_pad", "lily_pad", "lily_pad", "lily_pad", "tangle_kelp", "tangle_kelp", "tangle_kelp", "tallnut", "tallnut", "squash", "squash", "jalapeno", "jalapeno", "spikeweed", "spikeweed", "repeater", "repeater", "threepeater", "snow_pea", "snow_pea", "pepper_mortar", "cactus_guard", "pulse_bulb", "wind_orchid", "puff_shroom", "fume_shroom", "hypno_shroom", "ice_shroom", "doom_shroom", "prism_grass", "lantern_bloom", "meteor_gourd", "root_snare", "thunder_pine", "dream_drum", "wallnut", "potato_mine", "cherry_bomb", "torchwood", "amber_shooter", "vine_lasher"],
			"unlock_plant": "",
			"start_sun": 0,
			"row_count": 6,
			"time_scale": 0.76,
			"sky_sun_range": Vector2(999.0, 999.0),
			"node_pos": Vector2(760.0, 232.0),
			"events": [
				{"time": 5.0, "kind": "normal", "row": 0},
				{"time": 8.0, "kind": "lifebuoy_normal", "row": 2},
				{"time": 11.0, "kind": "conehead", "row": 5},
				{"time": 14.0, "kind": "snorkel", "row": 3},
				{"time": 17.0, "kind": "newspaper", "row": 1},
				{"time": 20.0, "kind": "pole_vault", "row": 4},
				{"time": 24.0, "kind": "flag", "wave": true},
				{"time": 25.0, "kind": "dolphin_rider", "row": 2},
				{"time": 29.0, "kind": "screen_door", "row": 0},
				{"time": 33.0, "kind": "farmer", "row": 5},
				{"time": 37.0, "kind": "lifebuoy_cone", "row": 3},
				{"time": 41.0, "kind": "spear", "row": 1},
				{"time": 45.0, "kind": "basketball", "row": 4},
				{"time": 49.0, "kind": "flag", "wave": true},
				{"time": 50.0, "kind": "buckethead", "row": 0},
				{"time": 54.0, "kind": "kungfu", "row": 5},
				{"time": 58.0, "kind": "football", "row": 1},
				{"time": 62.0, "kind": "zomboni", "row": 2},
				{"time": 66.0, "kind": "lifebuoy_bucket", "row": 3},
				{"time": 70.0, "kind": "ninja", "row": 4},
				{"time": 74.0, "kind": "flag", "wave": true},
				{"time": 75.0, "kind": "bobsled_team", "row": 2},
				{"time": 79.0, "kind": "nether", "row": 5},
				{"time": 83.0, "kind": "dancing", "row": 1},
				{"time": 87.0, "kind": "nezha", "row": 0},
				{"time": 91.0, "kind": "dark_football", "row": 4},
				{"time": 97.0, "kind": "flag", "wave": true},
			],
		},
		{
			"id": "1-17",
			"title": "白天 1-17",
			"description": "血月下的白天支线。露米娅盘踞在草坪右侧上空，以黑暗领域、夜鸟弹幕与召唤压制整片战场。",
			"terrain": "blood_moon",
			"mode": "conveyor",
			"boss_level": true,
			"unlock_requirements": ["2-10"],
			"available_plants": ["peashooter", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "wind_orchid", "puff_shroom", "fume_shroom", "hypno_shroom", "scaredy_shroom", "ice_shroom", "doom_shroom", "squash"],
			"conveyor_plants": ["peashooter", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "wind_orchid", "puff_shroom", "puff_shroom", "fume_shroom", "fume_shroom", "hypno_shroom", "scaredy_shroom", "ice_shroom", "doom_shroom", "squash", "cherry_bomb"],
			"unlock_plant": "",
			"start_sun": 0,
			"row_count": 5,
			"time_scale": 0.82,
			"sky_sun_range": Vector2(99.0, 99.0),
			"node_pos": Vector2(1692.0, 342.0),
			"boss_intro_bgm": "res://audio/rumia_intro.mp3",
			"boss_bgm": "res://audio/rumia_boss.mp3",
			"events": [
				{"time": 5.0, "kind": "conehead", "row": 1},
				{"time": 9.0, "kind": "flag", "wave": true},
				{"time": 9.6, "kind": "buckethead", "row": 3},
				{"time": 14.0, "kind": "screen_door", "row": 0},
				{"time": 18.0, "kind": "flag", "wave": true},
				{"time": 18.6, "kind": "dancing", "row": 2},
				{"time": 23.0, "kind": "ninja", "row": 4},
				{"time": 27.0, "kind": "flag", "wave": true},
				{"time": 27.8, "kind": "football", "row": 1},
				{"time": 33.0, "kind": "nether", "row": 2},
				{"time": 38.0, "kind": "flag", "wave": true},
				{"time": 38.6, "kind": "basketball", "row": 4},
				{"time": 44.0, "kind": "dark_football", "row": 0},
				{"time": 49.0, "kind": "flag", "wave": true},
				{"time": 49.6, "kind": "screen_door", "row": 2},
				{"time": 55.0, "kind": "nezha", "row": 3},
				{"time": 61.0, "kind": "rumia_boss", "wave": true},
			],
		},
		{
			"id": "1-18",
			"title": "白天 1-18",
			"description": "冰晶支线。左侧五列是寒湖水域，右侧四列仍是草地；大妖精会在半程拦截，琪露诺则会把整片湖面冻成冰场。",
			"terrain": "frozen_lake",
			"mode": "conveyor",
			"boss_level": true,
			"unlock_requirements": ["1-17", "3-4"],
			"row_count": 5,
			"start_sun": 0,
			"time_scale": 0.8,
			"sky_sun_range": Vector2(99.0, 99.0),
			"node_pos": Vector2(1864.0, 334.0),
			"mid_boss_kind": "daiyousei_boss",
			"boss_intro_bgm": "res://audio/cirno_intro.mp3",
			"boss_bgm": "res://audio/cirno_boss.mp3",
			"frozen_attack_slow": 1.3,
			"cell_terrain_mask": [
				["water", "water", "water", "water", "water", "land", "land", "land", "land"],
				["water", "water", "water", "water", "water", "land", "land", "land", "land"],
				["water", "water", "water", "water", "water", "land", "land", "land", "land"],
				["water", "water", "water", "water", "water", "land", "land", "land", "land"],
				["water", "water", "water", "water", "water", "land", "land", "land", "land"],
			],
			"available_plants": ["peashooter", "cherry_bomb", "wallnut", "potato_mine", "snow_pea", "chomper", "repeater", "amber_shooter", "vine_lasher", "pepper_mortar", "cactus_guard", "pulse_bulb", "wind_orchid", "puff_shroom", "fume_shroom", "hypno_shroom", "scaredy_shroom", "ice_shroom", "doom_shroom", "prism_grass", "lantern_bloom", "meteor_gourd", "root_snare", "thunder_pine", "dream_drum", "lily_pad", "squash", "threepeater", "tangle_kelp", "jalapeno", "spikeweed", "torchwood", "tallnut"],
			"conveyor_plants": ["lily_pad", "lily_pad", "lily_pad", "lily_pad", "lily_pad", "lily_pad", "tangle_kelp", "tangle_kelp", "snow_pea", "snow_pea", "ice_shroom", "repeater", "threepeater", "wallnut", "tallnut", "jalapeno", "squash", "pepper_mortar", "cactus_guard", "pulse_bulb", "wind_orchid", "prism_grass", "doom_shroom", "cherry_bomb"],
			"conveyor_plants_after_freeze": ["snow_pea", "snow_pea", "ice_shroom", "ice_shroom", "repeater", "threepeater", "wallnut", "tallnut", "jalapeno", "squash", "pepper_mortar", "cactus_guard", "pulse_bulb", "wind_orchid", "prism_grass", "lantern_bloom", "meteor_gourd", "root_snare", "thunder_pine", "dream_drum", "doom_shroom", "cherry_bomb", "spikeweed", "torchwood"],
			"events": [
				{"time": 5.0, "kind": "normal", "row": 0},
				{"time": 8.0, "kind": "lifebuoy_normal", "row": 2},
				{"time": 12.0, "kind": "conehead", "row": 4},
				{"time": 16.0, "kind": "snorkel", "row": 1, "wave": true},
				{"time": 22.0, "kind": "newspaper", "row": 3},
				{"time": 27.0, "kind": "lifebuoy_cone", "row": 0},
				{"time": 33.0, "kind": "screen_door", "row": 2, "wave": true},
				{"time": 39.0, "kind": "dolphin_rider", "row": 4},
				{"time": 44.0, "kind": "basketball", "row": 1},
				{"time": 50.0, "kind": "lifebuoy_bucket", "row": 3, "wave": true},
				{"time": 58.0, "kind": "kungfu", "row": 0},
				{"time": 63.0, "kind": "football", "row": 2},
				{"time": 69.0, "kind": "dark_football", "row": 4, "wave": true},
				{"time": 77.0, "kind": "ninja", "row": 1},
				{"time": 84.0, "kind": "cirno_boss", "wave": true},
			],
		},
	]
